added StartScreenFragment
WoodyMSK/SocialApp pull request #1
Opened 2023-07-06 20:26 UTC by WoodyMSK

2023-07-06 20:48 UTC, tyupik requested changes

2023-07-06 20:48 UTC, tyupik commented on app/build.gradle
> +    implementation("androidx.room:room-paging:2.5.2")
Посмотри на будущее, как оформлять зависимости. Версии (в данном случае 2.5.2) выносить в переменную, а тут подставлять уже переменную. Потому что если захочешь повысить версию библиотеки, то нужно будет лишь в одном месте поменять, а так тебе искать везде, где используется библиотека и везде править версию.

2023-07-06 20:48 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/activity/MainActivity.kt
> +
Лишняя строка

2023-07-06 20:48 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +
Лишняя строка

2023-07-06 20:48 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +
Лишняя строка

2023-07-06 20:48 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_marginEnd="70dp"
Лучше объединить в `android:paddingHorizontal="70dp"`

2023-07-06 20:48 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_height="338dp"
какие-то странные значения. На разных размерах экранов надо проверить, как будет выглядеть. Либо т.к. у тебя `ConstraintLayout`, задать точно, где будут границы вьюхи.

2023-07-06 20:48 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:id="@+id/imageView"
id для элементов лучше указывать в виде ivStartScreenAvatar: iv - тип вьюхи, в данном случае ImageView, далее на каком экране, далее что будет в этой вьюхе

2023-07-06 20:48 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_width="156dp"
Тоже посмотреть размеры. 
Возможно, лучше задать ширину match_parent и добавить horizontalPadding

2023-07-06 20:48 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_width="156dp"
То же самое

2023-07-06 20:48 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +
Куча лишних строк

2023-07-06 20:59 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +package ru.woodymsk.socialapp.activity
фрагмент лежит в пакете activity - неправильно. Это же не активити. 
Сделай отдельный пакет ui, там будет фрагмент, viewModel.

2023-07-06 21:10 UTC, tyupik commented on app/build.gradle
>      testImplementation 'junit:junit:4.13.2'
Проверь еще внимательно, все ли зависимости тебе действительно нужны. Потому что юнит-тесты ты в этом проекте вряд ли писать будешь, например.
И приведи все зависимости к одному виду, а то где-то есть скобки, где-то нет и тд.

2023-07-06 21:13 UTC, tyupik commented on app/src/main/AndroidManifest.xml
Сделай так, чтобы приложение было только в портретном виде и не переворачивалось. Потому что сейчас это выглядит криво. Не стоит пока заморачиваться с альбомной ориентацией

2023-07-08 12:32 UTC, WoodyMSK commented on app/build.gradle
> +    implementation("androidx.room:room-paging:2.5.2")
Отрефакторил

2023-07-08 12:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/activity/MainActivity.kt
> +
Удалил лишнюю строку

2023-07-08 12:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +
Удалил лишнюю строку

2023-07-08 12:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +
Удалил лишнюю строку

2023-07-08 12:44 UTC, WoodyMSK commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_marginEnd="70dp"
Объединил. Строки удалил:
        android:layout_marginStart="70dp"
        android:layout_marginEnd="70dp"

2023-07-08 12:45 UTC, WoodyMSK commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_height="338dp"
Округлил числа, чтобы не бросались в глаза

2023-07-08 12:46 UTC, WoodyMSK commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:id="@+id/imageView"
Исправил. Это я прям упустил

2023-07-08 13:01 UTC, WoodyMSK commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_width="156dp"
я привёл ширину кнопок "entryButton", "registrationButton" к ровным значениям. С параметрами ширины "match_parent" и добавлением "horizontalPadding" у меня какая-то фигня получается

2023-07-08 13:01 UTC, WoodyMSK commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:layout_width="156dp"
я привёл ширину кнопок "entryButton", "registrationButton" к ровным значениям. С параметрами ширины "match_parent" и добавлением "horizontalPadding" у меня какая-то фигня получается

2023-07-08 13:02 UTC, WoodyMSK commented on app/src/main/res/layout/fragment_start_screen.xml
> +
удалил лишние

2023-07-08 13:05 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +package ru.woodymsk.socialapp.activity
Исправил. Мне тоже не нравилось как это выглядело

2023-07-08 13:10 UTC, WoodyMSK commented on app/build.gradle
>      testImplementation 'junit:junit:4.13.2'
удалил лишние зависимости, которые, на мой взгляд, не понадобятся

2023-07-08 13:14 UTC, WoodyMSK commented on app/src/main/AndroidManifest.xml
Зафиксировал. 
А как теперь проверить, что MVVM работает?))

2023-07-08 13:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/activity/StartScreenFragment.kt
> +package ru.woodymsk.socialapp.activity
пакет "activity" тоже в пакет "ui" положил, надеюсь, так нормально.

2023-07-08 13:28 UTC, WoodyMSK commented
Удалил ToolBar

2023-07-09 07:18 UTC, tyupik commented on app/src/main/AndroidManifest.xml
а как это связано с MVVM?

2023-07-09 07:45 UTC, tyupik requested changes

2023-07-09 07:45 UTC, tyupik commented on app/src/main/java/ui/activity/MainActivity.kt
> +package ui.activity
а куда делся путь `ru.woodymsk.socialapp`? Его надо оставить

2023-07-09 07:45 UTC, tyupik commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/fragmentContainer"
не поменял

2023-07-09 07:45 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:id="@+id/entryButton"
не поменял

2023-07-09 07:45 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:id="@+id/registrationButton"
не поменял

2023-07-09 07:45 UTC, tyupik commented on app/src/main/res/layout/fragment_start_screen.xml
> +        android:paddingHorizontal="16dp"
Если делать все вообще по красоте, то надо такие базовые значени, как 4, 8, 16 dp и остальные, которые в одних и тех же местах используются, выносить в dimens и брать их оттуда.

2023-07-09 07:47 UTC, tyupik commented
Делай amend коммитов и потом force push, чтобы не плодить кучу ненужных коммитов

2023-07-09 08:07 UTC, WoodyMSK commented on app/src/main/AndroidManifest.xml
ViewModel хранит в себе состояние, которое передаёт фрагменту. Чтобы это проверить достаточно повернуть экран. В этом случае фрагмент пересоздаётся, если данные в нём останутся прежние (до поворота), то MVVM работает.

2023-07-09 08:16 UTC, tyupik commented on app/src/main/AndroidManifest.xml
Фрагмент подписывается на LivaData, подписчик живет, пока жив фрагмент, так что не отпишется ничего)
Ну и MVVM - это лишь паттерн. По твоей логике получается, что при MVP или MVI при повороте ничего сохраняться не будет?
Не заморачивайся, все будет работать)

2023-07-09 18:15 UTC, tyupik approved these changes

2023-07-09 18:16 UTC, merged