add event business logic
WoodyMSK/SocialApp pull request #11
Opened 2023-08-11 18:33 UTC by WoodyMSK

2023-08-11 19:03 UTC, tyupik requested changes

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/api/AuthService.kt
> +    suspend fun authUser(@Field("login") login: String, @Field("password") password: String): Response<Token>
раздели по строкам, а то в одну нечитабельно

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/AppAuth.kt
> +    private val idKey = "id"
в companion object и private const val

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    var user: LoggedInUser? = null
почему не приватная переменная?

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    val isLoggedIn: Boolean
тот же вопрос

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    fun logout() {
ты где-то помимо этого файла используешь эту функцию? Если да, почему ее нет в LoginRepository? Если нет, почему она не приватная?

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/model/LoggedInUser.kt
> +data class LoggedInUser(
В чем принципиальное отличие от RegisteredInUser?

2023-08-11 19:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    ): SharedPreferences = context.getSharedPreferences("auth", Context.MODE_PRIVATE)
Все строки выноси в переменные

2023-08-11 19:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/api/AuthService.kt
> +    suspend fun authUser(@Field("login") login: String, @Field("password") password: String): Response<Token>
сделал

2023-08-11 19:44 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/AppAuth.kt
> +    private val idKey = "id"
Сделал

2023-08-11 19:50 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    var user: LoggedInUser? = null
добавил private к var user.
private set убрал

2023-08-11 19:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    val isLoggedIn: Boolean
добавил private

2023-08-11 20:20 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    fun logout() {
добавил в LoginRepository

2023-08-11 20:36 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/model/LoggedInUser.kt
> +data class LoggedInUser(
я точно пока не знаю как точно использовать эти сущности. 
По сути они не отличаются, только по названию. 
Вот если запрашивать внутри приложения залогинен или нет - имеет смысл, а вот зарегестрирован или нет, мне кажется нет.

2023-08-11 20:37 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/model/LoggedInUser.kt
> +data class LoggedInUser(
есть ощущение, что RegisteredInUser можно удалить

2023-08-11 20:45 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    ): SharedPreferences = context.getSharedPreferences("auth", Context.MODE_PRIVATE)
я чёт попробовал добавить "@string/auth", но когда я зажимаю Ctrl и навожу курсором, текст "@string/auth" не становится гиперссылкой

2023-08-11 20:48 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    ): SharedPreferences = context.getSharedPreferences("auth", Context.MODE_PRIVATE)
я ведь верно понял?

2023-08-11 21:03 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    ): SharedPreferences = context.getSharedPreferences("auth", Context.MODE_PRIVATE)
Не работает с "@string/auth". Крашится приложение

2023-08-12 17:05 UTC, tyupik requested changes

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/AppAuth.kt
> +        _authStateFlow.value = Token()
А здесь точно надо токен передавать? Ты ведь вроде убираешь авторизацию.
Возможно, я путаю, конечно, что-то.

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    private val isLoggedIn: Boolean
Давай переименуем на `isUserAuthorized`, более понятно будет

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +        user = null
а здесь еще не хочешь вызвать `auth.removeAuth()`?

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/RegistrationRepositoryImpl.kt
> +        auth.setAuth(body.id, body.token ?: throw ApiError(response.message()))
по-моему, здесь избыточен элвис и все, что после него. Если будет null, то упадет строчкой выше

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/model/LoggedInUser.kt
> +data class LoggedInUser(
если есть ощущение, то удаляй, чтобы ничего лишнего не было

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            type = it.type.orOffline(),
не, вот `orOffline` не надо экстеншн, фигня какая-то. Это не унивирсально вообще. Тут лучше через элвис, а экстеншн удали.

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            participantsIds= it.participantsIds.orEmptyList(),
вроде можно просто orEmpty(), проверь

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    ): SharedPreferences = context.getSharedPreferences("auth", Context.MODE_PRIVATE)
Возможно, в шаредах нельзя так, оставь как есть тогда

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +var SharedPreferences.token: String?
тут точно var?

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun EventType?.orOffline(): EventType = this ?: OFFLINE
Это не надо, удали

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +        supervisorScope {
здесь это не нужно

2023-08-12 17:05 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    println("CoroutineExceptionHandler got $exception")
Вместо этого вызови лучше `AppError.from(exception)`. Там уже в зависимости от ошибки делай какие-либо действия.

2023-08-12 18:45 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/model/LoggedInUser.kt
> +data class LoggedInUser(
Удалил

2023-08-12 18:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/AppAuth.kt
> +        _authStateFlow.value = Token()
Насколько я понял, В строке
_authStateFlow.value = Token()
мы приводим его в дефолтное состояние
data class Token(
    val id: Int = 0,
    val token: String? = null,
)

2023-08-12 18:50 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    private val isLoggedIn: Boolean
Да, давай. Переименовал

2023-08-12 18:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +        user = null
Да, хочу)

2023-08-12 18:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/RegistrationRepositoryImpl.kt
> +        auth.setAuth(body.id, body.token ?: throw ApiError(response.message()))
я так и хотел сделать, но сам токен приходит "String?" и без отловки ошибки компилятор не пропускает . 
Мне кажется, если в body вместо token будет null, а id не null, то строкой выше не упадёт, а тут упадёт.

2023-08-12 19:03 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            type = it.type.orOffline(),
Порнография?
Переделал

2023-08-12 19:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            participantsIds= it.participantsIds.orEmptyList(),
Да, действительно можно. Удалил orEmptyList()

2023-08-12 19:12 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +var SharedPreferences.token: String?
с val компилятор ругается на сеттер
    set(value) {
        edit { putString(KEY, value) }
    }

2023-08-12 19:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun EventType?.orOffline(): EventType = this ?: OFFLINE
удалил

2023-08-12 19:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +        supervisorScope {
удалил

2023-08-12 19:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +        supervisorScope {
в ивентах тоже

2023-08-12 19:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    println("CoroutineExceptionHandler got $exception")
Да, так лучше

2023-08-12 19:43 UTC, tyupik requested changes

2023-08-12 19:43 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    private val isLoggedIn: Boolean
где?

2023-08-12 19:43 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/RegistrationRepositoryImpl.kt
> +        auth.setAuth(body.id, body.token ?: throw ApiError(response.message()))
Не нравятся мне все равно в каждой строке  `?: throw`
Сделай тут withContextIo и засунь в конструктор хэндлер, так будешь отлавливать все ошибки

2023-08-12 19:43 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            type = it.type ?: OFFLINE,
Мне кажется, лучше оставлять null. И если ничего не пришло, то в ui просто скрывать это поле. А то делать все  ивенты онлайн и оффлайн - такое себе.

2023-08-12 19:43 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +        postMapper.mapToDao(response.body() ?: throw ApiError(response.message()))
тоже засунь хэндлер в `withContextIO` и убери `?: throw`

2023-08-13 10:59 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    private val isLoggedIn: Boolean
блин, тупанул, не то переименовал

2023-08-13 11:33 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/LoginRepositoryImpl.kt
> +    private val isLoggedIn: Boolean
Я тут подумал, что isLoggedIn, что isUserAuthorized пока тут не используются и непонятно зачем нужны. Поэтому решил их удалить. Если появится необходимость, то добавлю.
Состояние авторизации можно тянуть из SharedPreferences

2023-08-13 11:57 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            type = it.type ?: OFFLINE,
сделал

2023-08-13 12:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +        postMapper.mapToDao(response.body() ?: throw ApiError(response.message()))
сделал покрасивее

2023-08-13 12:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/auth/RegistrationRepositoryImpl.kt
> +        auth.setAuth(body.id, body.token ?: throw ApiError(response.message()))
сделал покрасивее

2023-08-13 13:33 UTC, tyupik requested changes

2023-08-13 13:33 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/EventViewHolder.kt
> +            }
Можно проще:
`tvCardEventEventFormat.isVisible = event.type != null`

2023-08-13 13:41 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/EventViewHolder.kt
> +            }
исправил

2023-08-13 13:43 UTC, tyupik approved these changes

2023-08-13 13:44 UTC, merged