add registration business and ui logic
WoodyMSK/SocialApp pull request #12
Opened 2023-08-17 21:04 UTC by WoodyMSK

2023-08-18 17:52 UTC, tyupik requested changes

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +    val imm =
что значит imm? Непонятное название переменной

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +                        navigateTo(MyProfileScreenFragment.newInstance(), false)
есть функция `navigateTo(..., ...)`. Второй пепременной у тебя написано `false`. Человек со стороны не поймет, что это такое, пока не провалится в функцию. Напиши имена аргументов, чтобы было понятно, что есть что.

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            )
Вынеси в отдельную приватную функцию, а в `onViewCreated `вызови ее

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            )
тоже вынеси в функцию

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                }
Мне не нравится, что здесь присутствуют функции, которые ты не используешь. Из этого можно сделать кастомную функцию, переопределить `beforeTextChanged`, `onTextChanged` и `afterTextChanged`: исли используются, то заполнять, если нет - `null`. Если поймешь, как это сделать - будет круто, если нет, пока забей, потом будем править в конце.

Но в любом случае этот лисенер вынести в приватную функцию, потому что у тебя куакая-то куча в `onViewCreated`

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +        val appContext = context?.applicationContext ?: return
зачем тебе applicationContext?

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +        Toast.makeText(appContext, welcome, Toast.LENGTH_LONG).show()
Вместо `appContext` сделай `requireActivity` или как-то так, точно не помню

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +        Toast.makeText(appContext, errorString, Toast.LENGTH_LONG).show()
то же самое

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    fun registration(login: String, password: String, name: String) = viewModelScope.launch {
вместо try - catch сделай viewModelScope.launch(coroutineExceptionHandler).
Добавь свой хэндлер и там обработай ошибки

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        }
Это еще что такое?
есть `when` для таких случаев. Убирай.

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    private fun isLengthValid(string: String): Boolean = string.length < 3
Что значит 3?
В константу вынеси (не ресурсы!) и дай название.

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        RegistrationFormState(isRegistrationDataValid = false)
Что это дает?

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                RegistrationResult(error = registration_failed)
А `R.string.` ты не забыл тут?

P.S. увидел, что в импорте. Но лучше так не делай. Оставь `R.string.registration_failed`

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationResult.kt
> +    val error: Int? = null,
Не катит. Нужен тут нужен силд класс.

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationFormState.kt
> +    val isRegistrationDataValid: Boolean = false,
тоже силд класс

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    etRegistrationScreenAddName.error = null
Это все точно нужно?

2023-08-18 17:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                Observer { registrationResult ->
`viewModel.registrationResult.observe(viewLifecycleOwner) { registrationResult ->`

и выше тоже. Так красивее

2023-08-18 19:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +    val imm =
Переименовал в inputMethodManager. Собственно отсюда и сокращение

2023-08-18 19:58 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +                        navigateTo(MyProfileScreenFragment.newInstance(), false)
сделал

2023-08-18 20:19 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            )
готово

2023-08-18 20:20 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            )
готово

2023-08-18 20:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +        Toast.makeText(appContext, welcome, Toast.LENGTH_LONG).show()
Да, действительно, requireActivity(). Заменил, работает

2023-08-18 20:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +        val appContext = context?.applicationContext ?: return
Заменил на requireActivity()

2023-08-18 20:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +        Toast.makeText(appContext, errorString, Toast.LENGTH_LONG).show()
Заменил на requireActivity()

2023-08-19 19:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    fun registration(login: String, password: String, name: String) = viewModelScope.launch {
Сделал отдельный локальный хендлер registrationResultHandler

2023-08-19 19:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        }
переделал

2023-08-19 19:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    private fun isLengthValid(string: String): Boolean = string.length < 3
Сделал отдельный файл "Constants", занёс туда "const val MIN_LENGTH = 3"

2023-08-19 20:04 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    private fun isLengthValid(string: String): Boolean = string.length < 3
Переделал
В этом де файле сделал
    companion object {
        const val MIN_STRING_LENGTH = 3
    }

2023-08-19 20:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        RegistrationFormState(isRegistrationDataValid = false)
Сейчас и без этой строки работает. 
Когда отлаживал вывод ошибок, были случаи когда после того как все условия для активации кнопки "регистрация" были соблюдены, что-то портишь (например, чтобы пароли не совпадали) кнопка "регистрация" всё равно была активна

2023-08-19 20:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        RegistrationFormState(isRegistrationDataValid = false)
Удалил строку

2023-08-19 20:17 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                RegistrationResult(error = registration_failed)
переделал

2023-08-20 19:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                RegistrationResult(error = registration_failed)
Сделал R.string.registration_failed

2023-08-20 20:09 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    etRegistrationScreenAddName.error = null
Да, без этого бывают ситуации, когда ты выполнил все условия активации кнопки "регистрация", эта кнопка активировалась, но ошибка продолжает гореть, хотя по факту её нету. 

Но немного подумав, я придумал как обойтись без этих строк. Перенёс строку 
                    bRegistrationScreenSignInButton.isEnabled =
                        registrationFormState.isRegistrationDataValid
в самый низ, чтобы сначала прошла проверка на ошибки, а потом уж кнопка активировалась.

2023-08-20 20:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                Observer { registrationResult ->
Переделал.
Да, так даже намного понятнее.

2023-08-20 20:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    etRegistrationScreenAddName.error = null
Строки удалил

2023-08-20 20:35 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                }
сейчас вынес afterTextChangedListener() приватную функцию из onViewCreated. Но ожидаемо пропал доступ к значениям полей логина , пароля и т.д. это разве можно порешать?

2023-08-20 20:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                }
Порешал. Просто "binding" выпал))

2023-08-20 20:46 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                }
С первой частью - переопределением ещё не разобрался, но ещё подумаю

2023-08-21 20:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationResult.kt
> +    val error: Int? = null,
Переделал

2023-08-21 20:11 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationFormState.kt
> +    val isRegistrationDataValid: Boolean = false,
Переделал

2023-08-22 19:12 UTC, tyupik requested changes

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    )
2 раза вижу этот код как минимум. Вынеси в отдельную функцию.

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun updateUiWithUser(model: RegisteredInUserView) {
ну тут не updateUi, а скорее `showGreetingToast`

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun showRegistrationFailed(@StringRes errorString: Int) {
```suggestion
    private fun showRegistrationFailedToast(@StringRes errorString: Int) {
```

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            registrationFormState ?: return@observe
а это точно нужно?

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    is RegistrationFormState.LoginError -> etRegistrationScreenAddLogin.error =
Сделай здесь и ниже импорты, чтобы было просто `LoginError` и т.д.

Также если условие и действие внутри `when` не помещается в одну строку, то нужно использовать `{ }`
```
when (...) {
    is ... -> {
        ...
    }
}
```

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            registrationResult ?: return@observe
Тот же вопрос

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                is RegistrationResult.Success -> {
Просто Success

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            validateRegistrationResult()
Это оставь внутри `onViewCreated`, а все остальное вынеси в отдельную функцию

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun validateRegistrationData() {
```suggestion
    private fun observeRegistrationFormState() {
```

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun validateRegistrationResult() {
```suggestion
    private fun observeRegistrationResult() {
```

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    showRegistrationFailed(registrationResult.error)
Вообще тост можешь прям тут показать, для чего тебе отдельная функция? Там одна строчка и никакой логики.

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        name: String
запятая

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                RegistrationFormState.LoginError(loginError = invalid_length)
R.string.

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +            isLengthValid(login) -> _registrationFormState.value =
А точно правильно условие здесь и ниже? А то выглядит так, что если длина валидна, то показываешь ошибку.

Опять же `when` и несколько строк - нужны скобки `{ }`

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +            !isPasswordValid(password, confirmPassword) -> _registrationFormState.value =
Тут правильно условие, а на других полях нет, похоже.

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        const val MIN_STRING_LENGTH = 3
Ян вышел из чата)

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationResult.kt
> +    data class Success(val success: RegisteredInUserView) : RegistrationResult()
Передай сюда просто имя пользователя, которое у тебя сейчас в классе `RegisteredInUserView`. Зачем он тебе вообще нужен?
Будет просто `data class Success(val userName: String) : RegistrationResult()`

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegisteredInUserView.kt
> +data class RegisteredInUserView(
лишний класс

2023-08-22 19:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationFormState.kt
> +    data class IsRegistrationDataValid(val isRegistrationDataValid: Boolean): RegistrationFormState()
Что за `Int`?
Ставь аннотацию `@StringRes`, если  это должна быть ссылка на ресурсы

2023-08-22 19:59 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    )
сделал private fun registration()

2023-08-22 20:00 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun updateUiWithUser(model: RegisteredInUserView) {
переименовал

2023-08-22 20:01 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun showRegistrationFailed(@StringRes errorString: Int) {
Переименовал

2023-08-22 20:07 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            registrationFormState ?: return@observe
С sealed классом, думаю, что уже нет

2023-08-22 20:08 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            registrationResult ?: return@observe
С sealed классом, думаю, что уже не нужно

2023-08-22 20:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    is RegistrationFormState.LoginError -> etRegistrationScreenAddLogin.error =
Импорты сделал. 
when переделал

2023-08-22 20:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                is RegistrationResult.Success -> {
импорты добавил

2023-08-22 20:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +            validateRegistrationResult()
сделал. Почти ничего не осталось )

2023-08-22 20:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun validateRegistrationData() {
Переименовал

2023-08-22 20:35 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    private fun validateRegistrationResult() {
Переименовал

2023-08-22 20:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    showRegistrationFailed(registrationResult.error)
Да, действительно

2023-08-22 20:41 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        name: String
упс, добавил

2023-08-22 20:43 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                RegistrationFormState.LoginError(loginError = invalid_length)
Для всех строк этой функции добавил R.string.

2023-08-22 20:47 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +            isLengthValid(login) -> _registrationFormState.value =
Переделал на !isLengthValid(login). 
when исправил

2023-08-22 20:48 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +            !isPasswordValid(password, confirmPassword) -> _registrationFormState.value =
Переделал на !isLengthValid()

2023-08-22 20:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        const val MIN_STRING_LENGTH = 3
Условие для логина переделал - не должно быть пустым

2023-08-22 21:04 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +        const val MIN_STRING_LENGTH = 3
Конечно же имя, переделал

2023-08-22 21:08 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationResult.kt
> +    data class Success(val success: RegisteredInUserView) : RegistrationResult()
Переделал. 
RegisteredInUserView удалил

2023-08-22 21:09 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegisteredInUserView.kt
> +data class RegisteredInUserView(
Удалил

2023-08-23 19:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +                    showRegistrationFailed(registrationResult.error)
Переделал

2023-08-23 19:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/model/RegistrationFormState.kt
> +    data class IsRegistrationDataValid(val isRegistrationDataValid: Boolean): RegistrationFormState()
Добавил @StringRes

2023-08-23 20:14 UTC, tyupik approved these changes

2023-08-23 20:14 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +
Коммент лучше сверху оставляй.
А если длинный, ты по-другому оформляй:
```
*/
/
/*
```

2023-08-23 20:17 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +
Удалил его

2023-08-23 20:18 UTC, merged