add auth business and ui logic
WoodyMSK/SocialApp pull request #13
Opened 2023-08-27 19:18 UTC by WoodyMSK

2023-08-27 19:53 UTC, tyupik requested changes

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +        fun from(e: Throwable): AppError {
назови функцию не `from`, а `handleError`

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    object ConfirmPasswordError : AppError("Ошибка в логине или пароле")
Лучше уж _"Неверный логин или пароль"_, а то фамильярно как-то.


а вообще у респонса есть вроде бы errorBody, перепроверь, там должна лежать переменная `reason` из сваггера, вот ее надо сюда выводить.

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    object ServerError : AppError("Ошибка сервера")
и здесь то же самое

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        binding.bAuthScreenRegistration.setOnClickListener { onRegistrationClick() }
что ж ты так любишь скрин) в целом и так понятно, что это экран

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    data class Success(@StringRes val greeting: Int) : AppError(greeting.toString())
Почему `Success` в `Error` лежит? Нелогично.

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthViewModel.kt
> +        _authResult.value = AppError.Success(R.string.welcome)
Прям диссонанс какой-то: `Error` и следом `Success`. Подумай, как это можно еще сделать.

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthViewModel.kt
> +    }
```
_authFormState.value = when {
    login.isBlank() -> LoginError(loginError = R.string.is_blank)
    ....
и т.д.
}
```

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/model/AuthFormState.kt
> +    data class IsAuthDataValid(val isAuthDataValid: Boolean): AuthFormState()
А у тебя где-то используется `isAuthDataValid = false`? Нужен здесь вообще дата класс?

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +                    Toast.makeText(requireActivity(), authResult.code, Toast.LENGTH_LONG).show()
Это мне не нравится, комменты выше писал уже. Нужно переделать как-то по-нормальному.

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthTextChangedListener.kt
> +class AuthTextChangedListener(private val onTextChanged: () -> Unit) : TextWatcher {
зачем тебе на каждый экран одинаковый лисенер?
Сделай один с универсальным именем, положи в какую-нибудь общую папку и бери его.

2023-08-27 19:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +            bAuthScreenSignIn.isGone = false
Раздели экраны

2023-08-28 11:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +        fun from(e: Throwable): AppError {
Переименовал

2023-08-28 11:57 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    object ConfirmPasswordError : AppError("Ошибка в логине или пароле")
Переименовал. 
Вывод ошибки из reason оформим в отдельной задаче

2023-08-28 12:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    object ServerError : AppError("Ошибка сервера")
переименовал в "Что-то пошло не так"

2023-08-28 12:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    object ServerError : AppError("Ошибка сервера")
"Ошибка сервера" ->  "Что-то пошло не так"

2023-08-28 12:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/model/AuthFormState.kt
> +    data class IsAuthDataValid(val isAuthDataValid: Boolean): AuthFormState()
Это больше всё таки для красоты. Чтобы в функции authDataChecked в viewModel было что добавить в ветку else -> _authFormState.value = IsAuthDataValid(isAuthDataValid = true). 

"isAuthDataValid = false" не используется. 
Лучше убрать "data class IsAuthDataValid"?

2023-08-28 12:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthViewModel.kt
> +    }
спасибо, так лучше, скорректировал

2023-08-28 13:01 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/model/AuthFormState.kt
> +    data class IsAuthDataValid(val isAuthDataValid: Boolean): AuthFormState()
IsAuthDataValid переделал на object

2023-08-28 13:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/model/AuthFormState.kt
> +    data class IsAuthDataValid(val isAuthDataValid: Boolean): AuthFormState()
сделал один TextChangedListener. 
А если он будет лежать в папке auth? это норм?
Ведь, получается, что для экрана логина у меня будет своя папка.

2023-08-28 13:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthTextChangedListener.kt
> +class AuthTextChangedListener(private val onTextChanged: () -> Unit) : TextWatcher {
сделал один TextChangedListener.
А если он будет лежать в папке auth? это норм?
Ведь, получается, что для экрана логина у меня будет своя папка.

2023-08-28 13:18 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthTextChangedListener.kt
> +class AuthTextChangedListener(private val onTextChanged: () -> Unit) : TextWatcher {
сделал папку common, положил туда

2023-08-28 13:41 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        binding.bAuthScreenRegistration.setOnClickListener { onRegistrationClick() }
лучше вернуть как было?

2023-08-28 13:42 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        binding.bAuthScreenRegistration.setOnClickListener { onRegistrationClick() }
Наверное, да

2023-08-28 13:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        binding.bAuthScreenRegistration.setOnClickListener { onRegistrationClick() }
взад вернул. 
А где в принципе уместно добавлять "Screen" в названии?

2023-08-28 13:50 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        binding.bAuthScreenRegistration.setOnClickListener { onRegistrationClick() }
Когда чичероне будешь добавлять, вот там уместно

2023-08-28 19:31 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +            bAuthScreenSignIn.isGone = false
Экраны разделил. 
Добавил папки "login" во все слои. 
Где это логично переименовал auth в login, например, AuthRepository в LoginRepository. 
Верстку тоже всю перелопатил

2023-08-29 15:37 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/error/AppError.kt
> +    data class Success(@StringRes val greeting: Int) : AppError(greeting.toString())
Всё переделал. Теперь д.б. логично

2023-08-29 15:37 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthViewModel.kt
> +        _authResult.value = AppError.Success(R.string.welcome)
Всё переделал

2023-08-29 15:37 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +                    Toast.makeText(requireActivity(), authResult.code, Toast.LENGTH_LONG).show()
Всё переделал

2023-08-29 18:54 UTC, tyupik requested changes

2023-08-29 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    }
в целом  тебя тут никакой логики нет, просто вызывается вьюмодель, поэтому можно избавиться от этой функции и вынести сразу в место вызова

2023-08-29 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    }
это тоже

2023-08-29 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +                }
можно в одну строку и без скобок квадратных

2023-08-29 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +                false
а это что дает?

2023-08-29 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/model/LoginEvents.kt
> +}
отформатируй через ctrl+alt+L, явно видно, что это не сделано

2023-08-29 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                LoginError(loginError = R.string.invalid_length)
Выглядит так, что можно в одну строчку уместить и без скобок. Ниже тоже, проверь.

2023-08-29 19:24 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    }
по-моему так делали, потому что эта функция вызывается в двух местах. На 50 и 108

2023-08-29 19:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    }
вынес в место вызова. 
Но так, вроде лаконичный смотрелось

2023-08-29 19:30 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +                }
да, так лучше

2023-08-29 19:30 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +                false
без false ругается компилятор

2023-08-29 19:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/model/LoginEvents.kt
> +}
сделал

2023-08-29 19:35 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +                LoginError(loginError = R.string.invalid_length)
да, действительно помещается. Сделал тут и на других строках этой функции

2023-08-29 19:51 UTC, tyupik approved these changes

2023-08-29 19:52 UTC, merged