add realization post paging in domain presentation layers
WoodyMSK/SocialApp pull request #18
Opened 2023-09-16 12:23 UTC by WoodyMSK

2023-09-16 14:01 UTC, tyupik requested changes

2023-09-16 14:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                is LoadParams.Prepend -> return@withContextIO Page(
на одну строку не помещается, лучше скобки поставить. И `return` можно убрать, без него будет работать

2023-09-16 14:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun getPagedPostList(): Flow<PagingData<PostDAO>> = Pager(
`Pager(` перенеси на новую строку

2023-09-16 14:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/mapper/PostMapper.kt
> +                attachment = postDAO.attachment
запятую поставь

2023-09-16 14:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +        lifecycleScope.launch {
а через `observeFlow` нельзя что ли?

2023-09-16 14:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    val posts: Flow<PagingData<Post>>
а как в `posts` попадает `_posts`? Геттера не вижу

2023-09-16 14:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostsPost.kt
> +sealed class PostsPost {
это где-то используется?

2023-09-16 14:01 UTC, tyupik commented on core-coroutine/src/main/java/ru/woodymsk/socialapp/core_coroutine/util/PostFlow.kt
> +class PostFlow<T> : FlowCollector<T>, Flow<T> {
странно, что это тут отображается. Это ведь влито уже в девелоп ветку?

2023-09-17 10:57 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                is LoadParams.Prepend -> return@withContextIO Page(
поставил скобки, перенёс на новую строку. 
Без return компилятор подсвечивает красным body в строке:
val postList = result.body().orEmpty()

2023-09-17 10:58 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun getPagedPostList(): Flow<PagingData<PostDAO>> = Pager(
перенёс

2023-09-17 10:58 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/mapper/PostMapper.kt
> +                attachment = postDAO.attachment
поставил

2023-09-17 11:46 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +        lifecycleScope.launch {
observeFlow тоже работает. Это я прощелкал. 
Экстеншн observeFlow  позволит нам более эффективно использовать ресурсы. Потому что, при использовании lifecycleScope.launch, callbackFlow продолжает отправлять местоположения, когда фрагмент не отображается.
 А в с использованием observeFlow мы будем отписываться от flow, когда фрагмент не отображается. 
Я понял так

2023-09-17 11:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    val posts: Flow<PagingData<Post>>
Он в блоке init. 
    init {
        posts = _posts.asFlow()
            .flatMapLatest {
                postInteractor.getPagedPostList()
            }
            .cachedIn(viewModelScope)
    }

2023-09-17 11:52 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostsPost.kt
> +sealed class PostsPost {
Сейчас не используется. Не хотел терять реализацию. Но если, что в этой ветка она есть для ивентов. Смогу там всегда глянуть.

2023-09-17 11:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostsPost.kt
> +sealed class PostsPost {
Удалил

2023-09-17 11:57 UTC, WoodyMSK commented on core-coroutine/src/main/java/ru/woodymsk/socialapp/core_coroutine/util/PostFlow.kt
> +class PostFlow<T> : FlowCollector<T>, Flow<T> {
В девелоп для ивентов должно быть. Здесь я делал реализацию для постов. 
Удалил т.к. не используется.

2023-09-17 12:32 UTC, tyupik requested changes

2023-09-17 12:32 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                )
Несколько строк -> должны быть скобки

2023-09-17 12:32 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun getPagedPostList(): Flow<PagingData<PostDAO>> =
а почему убрал `withContextIO`?

2023-09-17 13:43 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                )
да, не доглядел

2023-09-17 13:45 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun getPagedPostList(): Flow<PagingData<PostDAO>> =
Вернул. 
Видимо случайно удалил после множественных переписок кода для тестов

2023-09-20 18:36 UTC, tyupik requested changes

2023-09-20 18:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                return@withContextIO Error(e)
а тут не получится обработать через AppError как-нибудь?

2023-09-20 18:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    private val postsReceiveHandler = CoroutineExceptionHandler { _, exception ->
да для унификации можешь везде называть просто exceptionHandler и все, не обязательно в каждоый вьюмодели по-совему

2023-09-20 18:57 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    private val postsReceiveHandler = CoroutineExceptionHandler { _, exception ->
согласен, переименовал

2023-09-20 20:22 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                return@withContextIO Error(e)
Тут уж сам подсобил ))

2023-09-20 20:23 UTC, tyupik approved these changes

2023-09-20 20:24 UTC, merged