added post load indicator
WoodyMSK/SocialApp pull request #20
Opened 2023-09-23 11:39 UTC by WoodyMSK

2023-09-23 11:45 UTC, tyupik requested changes

2023-09-23 11:45 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateViewHolder.kt
> +    private val onRetryListener: () -> Unit,
а где ты это используешь?

2023-09-25 11:38 UTC, tyupik requested changes

2023-09-25 11:38 UTC, tyupik commented on app/src/main/res/layout/item_load_state.xml
Поправить ui на тот, что обсудили

2023-09-26 09:42 UTC, tyupik requested changes

2023-09-26 09:42 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateAdapter.kt
> +        fun onRetry() {}
Так, ну есть у тебя интерфейс с функцией и пустым телом. Зачем?

2023-09-26 09:42 UTC, tyupik commented on app/src/main/res/layout/item_load_state.xml
> +        android:paddingTop="16dp"
не уверен, но выглядит так, что можно тут и во втором `TextView` убрать паддинги и добавть на `Group` один вертикальный паддинг

2023-09-26 09:42 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateViewHolder.kt
> +            grErrorLoadState.isVisible = state is LoadState.Error
Что-то тут не так. Когда жмешь кнопку повторить, то текст не скрывается, а просто смещается ниже,  а сверху появляется прогресс бар, так нее должно быть: либо текст, либо прогресс бар.

2023-09-26 09:42 UTC, tyupik commented on app/src/main/res/values/strings.xml
> +    <string name="error">Что-то пошло не так :(</string>
```suggestion
    <string name="something_went_wrong">Что-то пошло не так :(</string>
```

2023-09-26 18:46 UTC, WoodyMSK commented on app/src/main/res/layout/item_load_state.xml
ui облагородил

2023-09-26 19:07 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateAdapter.kt
> +        fun onRetry() {}
сократил количество кода, сделал красивее

2023-09-26 19:11 UTC, WoodyMSK commented on app/src/main/res/layout/item_load_state.xml
> +        android:paddingTop="16dp"
К сожалению, так не заработало, Group игнорирует паддинги

2023-09-26 19:12 UTC, WoodyMSK commented on app/src/main/res/values/strings.xml
> +    <string name="error">Что-то пошло не так :(</string>
Исправил

2023-09-27 19:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateViewHolder.kt
> +            grErrorLoadState.isVisible = state is LoadState.Error
сделали

2023-09-27 19:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateViewHolder.kt
> +            grErrorLoadState.isVisible = state is LoadState.Error
точней, исправили

2023-09-28 11:55 UTC, tyupik requested changes

2023-09-28 11:55 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateAdapter.kt
> +    LoadStateAdapter<PagingLoadStateViewHolder>() {
```suggestion
class PagingLoadStateAdapter(
    private val onRetryListener: () -> Unit,
)  :  LoadStateAdapter<PagingLoadStateViewHolder>() {
```

2023-09-28 11:55 UTC, tyupik commented on app/src/main/res/layout/item_load_state.xml
> +        android:padding="8dp"
по-моему, тут должен быть `paddingBottom`. При том раскладе, что сделал ты, суммарно высота 88 никак не получится: 8+36+8+36+8

2023-09-28 17:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateAdapter.kt
> +    LoadStateAdapter<PagingLoadStateViewHolder>() {
поправил

2023-09-28 17:12 UTC, WoodyMSK commented on app/src/main/res/layout/item_load_state.xml
> +        android:padding="8dp"
Поправил, по красоте. 
В принципе, оно с padding="8dp" не прыгало. Но для симметричности надо paddingBottom="8dp"

2023-09-28 17:27 UTC, tyupik approved these changes

2023-09-28 17:28 UTC, merged