Feature/add post like
WoodyMSK/SocialApp pull request #21
Opened 2023-10-08 14:15 UTC by WoodyMSK

2023-10-08 16:46 UTC, tyupik requested changes

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                    )
ты экстеншн сделал же

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +
лишняя

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/interactor/PostInteractor.kt
> +
лишняя

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/mapper/PostMapper.kt
> +            postDAO.likedByMe = postDAO.likeOwnerIds.contains(auth.authStateFlow.value.id)
не нужна, вставь это сразу ниже на 41 строчку

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    var likedByMe: Boolean,
никаких var'ов в моделях!

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    var likes: Int = likeOwnerIds.size,
!!!!

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateAdapter.kt
> +        return PagingLoadStateViewHolder(
можно без `return`, просто `=`, красивее будет

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateViewHolder.kt
> +    }
что-то я не понял, как это здесь оказалось.
Ты ведь уже вливал это в предыдущей ветке?!

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostClickListener.kt
> +    fun onLike(post: Post) {}
для чего тело пустое тут?

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                    }
если пользователь случайно нажал лайк, то ты его принудительно закидываешь на экран авторизации?
Сомнительный кейс. Тут лучше добавить `snackbar` или `BottomSheetDialogFragment`, например, а в нем по кнопке перекидывать уже на экран авторизации.

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +
что ж ты так любишь пустые строчки)

2023-10-08 16:46 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +                    post.likes--
кейс: у тебя загрузились посты, пропал интернет, ты нажал на лайк, что произойдет?

2023-10-08 18:08 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                    )
да, тут пропустил

2023-10-08 18:09 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +
удалил

2023-10-08 18:11 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/interactor/PostInteractor.kt
> +
удалил

2023-10-08 18:12 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/mapper/PostMapper.kt
> +            postDAO.likedByMe = postDAO.likeOwnerIds.contains(auth.authStateFlow.value.id)
скорректировал

2023-10-08 18:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateAdapter.kt
> +        return PagingLoadStateViewHolder(
угу, сделал

2023-10-08 18:17 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/PagingLoadStateViewHolder.kt
> +    }
честно говоря, я тоже не понимаю откуда тут это. На этапе проверки перед тем как сделать коммит, я не видел этих строк

2023-10-08 18:21 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostClickListener.kt
> +    fun onLike(post: Post) {}
действительно, незачем, убрал

2023-10-08 18:22 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +
угу(( убрал

2023-10-26 20:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    var likedByMe: Boolean,
Вернул val

2023-10-26 20:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    var likes: Int = likeOwnerIds.size,
Вернул val

2023-10-26 20:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +                    post.likes--
Всё переделал. Лайки теперь проставляются не непосредственно в UI, а запрашивается новый пул постов с обновленными данными, которые уже и обновляются в UI.
Теперь при ошибке количество не изменится, но кнопка покраснеет т.к. это заложено в её логике. Это нужно исправлять, так чтобы краснела/серела только при измении лайка?

2023-10-28 10:23 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    var likedByMe: Boolean,
Скорректировал

2023-10-28 10:27 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                    }
сделал DialogFragment - это норм?
Если норм, то попозже попробую разобраться с BottomSheetDialogFragment. С наскока не удалось найти понятную реализацию

2023-10-28 10:30 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                    }
Пойдет. Зальешь - посмотрю, как выглядит.

2023-10-28 10:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +                    post.likes--
Вообще желательно, чтобы если произошла ошибка, то лайк менял цвет обратно.

2023-10-28 10:31 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +                    post.likes--
Сейчас уже количество лайков не поменяется. Только кнопка всё равно станет красной(серой). Я так понимаю - это заложено в её логике на уровне UI

2023-10-28 11:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +                    post.likes--
сделал, чтобы картинка лайка не менялась, если произошла ошибка

2023-10-28 11:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +                    post.likes--
ток реализация, по-моему, не очень

2023-10-28 19:24 UTC, tyupik requested changes

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                        pageSize += 10
вынеси в константу

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +        private var pageSize = 10
зачем var  в companion object?

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +        private var pageSize = 10
и из названия я бы подумал, что это размер одной страницы, но далее в коде ты увеличиваешь эту переменную.

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/model/PostDAO.kt
> +    var likedByMe: Boolean,
var

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                        showLoginDialogFragment()
Сделал бы через snackbar) усложнил себе жизнь только сильно.
Ну ладно, сделал и сделал.

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    fun like(post: Post) =
Приватные функции не должны быть выше публичных.
И поменяй имя на `onLikeButtonClick`, например

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    fun like(post: Post) =
Плюс тут как-то плохо работает: лайк нажал, проходит 3 секунды, только после этого он проставляется. Нажал еще раз, чтобы убрать его, снова 3 секунды проходит. И так каждый раз.
Плюс вся карточка поста мигает.

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    val likes: Int = likeOwnerIds.size,
убери `Int`. Нигде нет, а тут зачем-то стоит.

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +            postInteractor.like(post)
Ну т.е. пользователь не авторизован, а ты все равно отправляешь рест с лайком и грузишь посты. Зачем?

2023-10-28 19:24 UTC, tyupik commented on app/src/main/res/values/strings.xml
> +    <string name="error_authorization">Ошибка авторизации</string>
Лучше не `"Ошибка авторизации"`, а что-нибудь типа `"Необходимо авторизоваться"`.

2023-10-28 19:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                DialogInterface.BUTTON_POSITIVE -> navigator().navigateTo(LoginFragment.newInstance())
А если пользователь не зарешестрирован? Ты его сразу авторизоваться заставляешь. Лучше кидай на экран, где кнопки "Зарегистрироваться" и "Войти" или как-то так они называются, не помню уже.

2023-10-29 11:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +        private var pageSize = 10
вытащил var из companion object. 
Переименовал pageSize в postsLoadSize. Это количество загружаемых постов , оно увеличивается на размер страницы, по мере пролистывания ленты.

2023-10-29 11:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                        pageSize += 10
вынес в константу
    companion object {
        const val PAGE_SIZE = 10
    }

2023-10-29 11:08 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/model/PostDAO.kt
> +    var likedByMe: Boolean,
простите потерял

2023-10-29 11:11 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/Post.kt
> +    val likes: Int = likeOwnerIds.size,
без явного указания типа компилятор ругается: "A type annotation is required on a value parameter"

2023-10-29 11:20 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +            postInteractor.like(post)
прописал прерывание выполнение функции return@launch. 
Перестали приходить ошибки с бэка о необходимости авторизации ))

2023-10-29 11:24 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +            postInteractor.like(post)
Добавил
                postInteractor.like(post)
                loadPagedPost()
в ветку else

2023-10-29 11:25 UTC, WoodyMSK commented on app/src/main/res/values/strings.xml
> +    <string name="error_authorization">Ошибка авторизации</string>
действительно, так лучше

2023-10-29 11:26 UTC, WoodyMSK commented on app/src/main/res/values/strings.xml
> +    <string name="error_authorization">Ошибка авторизации</string>
переделал

2023-10-29 11:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                DialogInterface.BUTTON_POSITIVE -> navigator().navigateTo(LoginFragment.newInstance())
переделал. 
Теперь закидываю на AuthFragment, где можно выбрать логин или регистрацию

2023-10-29 11:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                        pageSize += 10
сделал круче:
postsLoadSize += params.loadSize

params.loadSize задаётся константой const val PAGE_SIZE = 10 в конфигурации Pager в PostRepositoryImpl
            Pager(
                config = PagingConfig(
                    pageSize = PAGE_SIZE,
                    enablePlaceholders = false,
                ),

2023-10-29 16:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    fun like(post: Post) =
мерцание и моргание устранил. 
Только есть сомнение по поводу масштабирования этого метода.

2023-10-29 16:38 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    fun like(post: Post) =
функцию like переименовал, поднял выше приватных

2023-10-29 17:02 UTC, tyupik requested changes

2023-10-29 17:02 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                    }
вроде и в одну строчку поместится

2023-10-29 17:02 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +        payload.liked?.also { liked ->
тут по смыслу больше `let` подходит, а не `also`

2023-10-29 17:02 UTC, tyupik commented on app/src/main/res/layout/item_load_state.xml
> +        android:padding="8dp"
Точно?

2023-10-29 17:02 UTC, tyupik commented on app/src/main/res/values/strings.xml
> +    <string name="filter_symbol_name"><![CDATA[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя1234567890`~!@#$%^*()_-+={}[]|:;\'
Проверь, пробел работает? Мне лень собирать)  А то как написать фамилию и имя.

2023-10-29 17:02 UTC, tyupik commented on app/src/main/res/layout/item_card_post.xml
> +            android:checkable="false"
Точно?

2023-10-29 17:59 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostPageSource.kt
> +                    }
угу, поправил

2023-10-29 18:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewHolder.kt
> +        payload.liked?.also { liked ->
угу, поправил

2023-10-29 18:18 UTC, WoodyMSK commented on app/src/main/res/layout/item_load_state.xml
> +        android:padding="8dp"
paddingBottom ровнее смотрится, оставил его

2023-10-29 18:20 UTC, WoodyMSK commented on app/src/main/res/values/strings.xml
> +    <string name="filter_symbol_name"><![CDATA[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя1234567890`~!@#$%^*()_-+={}[]|:;\'
пробел добавил

2023-10-29 18:27 UTC, WoodyMSK commented on app/src/main/res/layout/item_card_post.xml
> +            android:checkable="false"
c android:checkable="true" тоже нормально работает. Вернул назад

2023-10-29 18:28 UTC, WoodyMSK commented on app/src/main/res/layout/item_card_post.xml
> +            android:checkable="false"
С другой стороны не принципиально т.к. картинку и цвет задаю принудительно

2023-10-29 18:42 UTC, tyupik approved these changes

2023-10-29 18:57 UTC, merged