Add new post business logic
WoodyMSK/SocialApp pull request #26
Opened 2023-11-10 18:36 UTC by WoodyMSK

2023-11-11 17:24 UTC, tyupik requested changes

2023-11-11 17:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun publishPost(postEntity: PostEntity) =
```suggestion
    override suspend fun createPost(postEntity: PostEntity) =
```

2023-11-11 17:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun publishPostWithAttachment(postEntity: PostEntity, upload: MediaUpload) =
```suggestion
    override suspend fun createPostWithAttachment(postEntity: PostEntity, upload: MediaUpload) =
```

2023-11-11 17:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +                "file", upload.file.name, upload.file.asRequestBody()
`file` в константы

2023-11-12 18:00 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun publishPost(postEntity: PostEntity) =
переименовал. 
В REST тоже переименовал функцию на createPost

2023-11-12 18:00 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun publishPostWithAttachment(postEntity: PostEntity, upload: MediaUpload) =
переименовал. 
В REST тоже переименовал функцию на createPost

2023-11-12 18:03 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +                "file", upload.file.name, upload.file.asRequestBody()
добавил. 
ещё добавил имена вызываемых аргументов

2023-11-12 18:53 UTC, tyupik approved these changes

2023-11-12 19:22 UTC, merged