Add new post ui logic
WoodyMSK/SocialApp pull request #27
Opened 2023-11-18 13:38 UTC by WoodyMSK

2023-11-18 20:32 UTC, tyupik requested changes

2023-11-18 20:32 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/interactor/PostInteractor.kt
> +    suspend fun createPostWithAttachment(post: Post, upload: MediaUpload) =
зачем тебе 2 функции? сделай одну, upload нулабельный и все

2023-11-18 20:32 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        const val IMAGE_JPEG = "image/jpeg"
private

2023-11-18 20:32 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +                    .provider(ImageProvider.GALLERY)
во-первых, это надо вынести в функцию в отдельный файл, потому что этот же код ты будешь использовать, когда будешь добавлять картинки в новый ивент, во-вторых, не вижу, где ты запрашиваешь пермишены на доступ к камере и галерее?

2023-11-19 15:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/interactor/PostInteractor.kt
> +    suspend fun createPostWithAttachment(post: Post, upload: MediaUpload) =
переделал

2023-11-19 15:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        const val IMAGE_JPEG = "image/jpeg"
добавил

2023-11-21 20:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +                    .provider(ImageProvider.GALLERY)
функцию вынес. Пермишены добавил

2023-11-22 14:08 UTC, tyupik requested changes

2023-11-22 14:08 UTC, tyupik commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
а зачем тебе видео? Ты ведь только фотки грузишь

2023-11-22 14:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun onGotPermissionResultForCamera(granted: Boolean) {
Надо вынести в отдельный файл и функцию, чтобы можно было вызвать из любого места. Такие методы должны быть универсальные и общедоступные.

2023-11-22 14:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun onGotPermissionResultForImages(grantResults: Map<String, Boolean>) {
та же фигня

2023-11-22 14:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun askUserForOpenAppSettings() {
the same shit

2023-11-22 14:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    private fun newPostHandleError(e: Throwable) =
можно объединить с методом `handleError`, они почти одинаковые, подумай как

2023-11-22 14:08 UTC, tyupik commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
а зачем ты указываешь тут `maxSdkVersion`?

2023-11-22 14:08 UTC, tyupik commented on app/src/main/AndroidManifest.xml
> +    <!-- Devices running Android 13 (API level 33) or higher -->
по-моему, это появилось в api 30, а не 33

2023-11-22 14:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private val viewModel: PostViewModel by viewModels()
а зачем ты одну вьюмодель используешь и на экран нового поста, и на список постов? Не надо так. Сделай отдельную вьюмодель, в этой лишняя логика для этого экрана. Заходишь ты на него, например, отправляется сразу рест на посты, и зачем это нужно?

2023-11-22 14:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +                }
Всю эту логику вынести в отдельный файл. Здесь вызывать только какую-то функцию и передавать туда, какой вид пермишена ты хочешь проверить, чтобы метод был универсальный.

2023-11-22 19:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private val viewModel: PostViewModel by viewModels()
Сделал.
Так, действительно, логичнее

2023-11-22 20:13 UTC, WoodyMSK commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
Когда выскакивает базовая картинка с просьбой предоставить доступ, там написано "Разрешить приложения SocialApp снимать фото и видео?". Поэтому решил добавить и видео

2023-11-22 20:57 UTC, WoodyMSK commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
Так велел гугл
https://developer.android.com/about/versions/14/changes/partial-photo-video-access
Как я понял, это официальный источник.

2023-11-22 21:01 UTC, WoodyMSK commented on app/src/main/AndroidManifest.xml
> +    <!-- Devices running Android 13 (API level 33) or higher -->
Судя по всему, всё таки с 13, другого варианта не нашёл. С 14 там ещё добавка

2023-11-22 21:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun onGotPermissionResultForCamera(granted: Boolean) {
Смущает то что многие функции, которые участвуют в запросе пермишина, просят activity и contect. Мне кажется, что им туда его передавать из фрагмента - это не лучшая идея. 
Вероятно, я ещё не вкурил как тут грамотно сделать

2023-11-24 21:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    private fun newPostHandleError(e: Throwable) =
я же выношу это в отдельную NewPostViewModel. Там этот хендлер я могу по сути как угодно назвать. Действительно как-то их стоит объединять?

2023-11-24 21:29 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    private fun newPostHandleError(e: Throwable) =
У каждой вьюмодели свой хендлер будет

2023-11-27 20:24 UTC, WoodyMSK commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
в итоге оставил только разрешение на картинки, потому что реально доступа к видео нет

2023-11-27 20:25 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun onGotPermissionResultForCamera(granted: Boolean) {
переработал с использованием экстеншн-функций

2023-11-27 20:25 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun onGotPermissionResultForImages(grantResults: Map<String, Boolean>) {
переработал с использованием экстеншн-функций

2023-11-27 20:25 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private fun askUserForOpenAppSettings() {
переработал с использованием экстеншн-функций

2023-11-27 20:27 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +                }
вынес в экстеншн-функцию, как и всё что связано с пермишенами

2023-11-28 19:36 UTC, tyupik requested changes

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun requestPermissions(request: ActivityResultLauncher<Array<String>>, permissions: Array<String>) =
то же самое, что и выше, только там не массив. Оставляй что-то одно

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun Fragment.isAllPermissionsGranted(permissions: Array<String>) = permissions.all {
то же самое

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun checkImagePermissionType(): String {
ну тут не check. Ты ведь получаешь "тип" пермишена. По названию можно подумать, что ты проверяешь, дан пермишен уже или нет. Подумай над названием.

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun requestPermission(request: ActivityResultLauncher<String>, permissions: String) =
Вынеси всё, что связано с пермишенами, в отдельный файл.

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private lateinit var permissionsCameraRequest: ActivityResultLauncher<String>
у тебя обе эти переменные используются внутри одной функции. Зачем ты вынесишь их на весь класс? Плюс это еще и lateinit. Убери отсюда.

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        permissionsCameraRequest = getCameraPermissionRequest()
здесь просто `val` добавить в начале строчки и все.

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        }
дву функции почти одинаковые. Добавь аргумент с типом пермишена и объедини.

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +import android.Manifest.permission.*
звездочка

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        permissionsCameraRequest = getCameraPermissionRequest()
что-то я не пойму, что здесь происходит.
Открывается экран, сразу проверяются пермишены, если они есть, то сразу запускает imagePicker что ли?

2023-11-28 19:36 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +                photoImagePicker.pickImage(requireActivity(), pickPhotoLauncher::launch)
в `onViewCreated` ты запускаешь эту функцию. если пермишен есть, то сразу открываешь `imagePicker`?

2023-11-28 19:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun requestPermissions(request: ActivityResultLauncher<Array<String>>, permissions: Array<String>) =
Удалил неиспользуемый requestPermissions. 
Тут идея была в том, чтобы за одну итерацию запрашивать сразу несколько разрешений

2023-11-28 19:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun Fragment.isAllPermissionsGranted(permissions: Array<String>) = permissions.all {
Удалил неиспользуемый isAllPermissionsGranted

2023-11-28 19:46 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun checkImagePermissionType(): String {
getImagePermissionType по-моему логичнее

2023-11-28 20:00 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun requestPermission(request: ActivityResultLauncher<String>, permissions: String) =
вынес в отдельный файл, в презентейшн слой

2023-11-28 20:12 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +    private lateinit var permissionsCameraRequest: ActivityResultLauncher<String>
сделал

2023-11-28 21:21 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        permissionsCameraRequest = getCameraPermissionRequest()
Переменные
        val permissionsImageRequest = getImagePermissionRequest()
        val permissionsCameraRequest = getCameraPermissionRequest()
Нам нужны чтобы инициализировать registerForActivityResult() . Если этого не сделать, то при запросе пермишена (после нажатия кнопки) приложение упадёт с соответствующей ошибкой "Fragments must call registerForActivityResult() before they are created (i.e. initialization, onAttach(), or onCreate())". 

При нажатии кнопки камеры или галереи запускается ActivityResultLauncher (с помощью экстеншн-функции requestPermission()), 

Далее, если всё хорошо запускается функция getImagePermissionRequest() или getCameraPermissionRequest(), где экстеншн-функцией isPermissionGranted() проверяется есть ли у нас разрешение уже:
true - запускается photoImagePicker
false - она же (isPermissionGranted()) запускает диалоговое окно c просьбой дать разрешение.

Если разрешение не дали, то запускается 
checkPermissionResult(CAMERA), где shouldShowRequestPermissionRationale() проверит отклоняли ли мы несколько раз пермишены до этого:
true - покажет тост
false - запустит диалоговое окно permissionsRequireDialogFragment() в предложение перейти в настройки и дать разрешения вручную.

2023-11-28 21:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +import android.Manifest.permission.*
Убрал

2023-11-28 21:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +                photoImagePicker.pickImage(requireActivity(), pickPhotoLauncher::launch)
нет, инициализирую обработчик событий registerForActivityResult(). 
imagePicker запускается только если пройдёт проверка isPermissionGranted(), которая запускается после нажатия соответствующей кнопки

2023-11-28 21:44 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        }
пробовал - не получилось, registerForActivityResult() довольно специфическая функция. Попробую ещё раз

2023-11-29 10:39 UTC, tyupik requested changes

2023-11-29 10:39 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun checkImagePermissionType(): String {
Тогда сделай лучше не `string`, а `enum`

2023-11-29 10:39 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        permissionsCameraRequest = getCameraPermissionRequest()
В таком случае тебе надо вызвать просто `registerForActivityResult(RequestPermission())`? а то ты и тут вызываешь `getImagePermissionRequest()`, и после нажатия на кнопку тоже.

2023-11-29 20:00 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun checkImagePermissionType(): String {
не получилось с enum. 
Сделал
enum class PermissionType {
    CAMERA,
    READ_MEDIA_IMAGES,
    READ_EXTERNAL_STORAGE,
}
В функции, которые принимают пермишены передавал PermissionType.toString():
shouldShowRequestPermissionRationale(PermissionType .toString())

ContextCompat.checkSelfPermission(
        requireContext(),
        PermissionType .toString(),
    ) == PERMISSION_GRANTED

request.launch(PermissionType .toString())

Но проверка на предоставление пермишена не проходит, даже если они все предоставлены. Сразу кидает на permissionsRequireDialogFragment()

2023-11-29 21:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        }
Замутил опять вот такую объединённую функцию

    private fun getPermissionRequest(permission: String): ActivityResultLauncher<String> {
        val permissionType = when(permission) {
            CAMERA -> photoImagePicker.takePhoto(requireActivity(), pickPhotoLauncher::launch)
            READ_MEDIA_IMAGES -> photoImagePicker.pickImage(requireActivity(), pickPhotoLauncher::launch)
            READ_EXTERNAL_STORAGE -> photoImagePicker.pickImage(requireActivity(), pickPhotoLauncher::launch)
            else -> {}
        }
        return registerForActivityResult(RequestPermission()) {
            if (isPermissionGranted(permission)) {
                permissionType
            } else {
                checkPermissionResult(permission)
            }
        }
    }

Чтобы не ругалась функция requestPermission(), для getPermissionRequest(permission: String) пришлось добавить возвращаемый тип ActivityResultLauncher<String>. 

Теперь при onViewCreated для нужно инициализировать registerForActivityResult вот так:

        val permissionsImageRequest = getPermissionRequest(getImagePermissionType())
        val permissionsCameraRequest = getPermissionRequest(CAMERA)
        
Теперь при запуске фрагмента NewPostFragment с инициализацией onViewCreated камера или галерея запускается автоматически, смотря что стоит первым в проверке when(permission) в getPermissionRequest(permission: String)

2023-11-30 19:12 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostViewModel.kt
> +    private fun newPostHandleError(e: Throwable) =
Переделал

2023-11-30 19:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Extensions.kt
> +fun checkImagePermissionType(): String {
оставил со String. С enum не работает

2023-11-30 19:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        permissionsCameraRequest = getCameraPermissionRequest()
отдельно registerForActivityResult(RequestPermission()) вызвать не получается - компилятор ругается

2023-11-30 19:27 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/NewPostFragment.kt
> +        }
оставил как есть

2023-11-30 20:58 UTC, tyupik approved these changes

2023-12-01 18:56 UTC, merged