Add post update
WoodyMSK/SocialApp pull request #28
Opened 2023-12-10 17:31 UTC by WoodyMSK

2023-12-10 18:09 UTC, tyupik requested changes

2023-12-10 18:09 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/login/LoginRepositoryImpl.kt
> +        postRepository.updateLoginPostOwned(body.id)
что-то мне не нравится этот подход. Ты при каждом логине и логауте будешь перебирать всю БД? А если там будут тысячи записей?

Предлагаю делать так: при создании поста на бэк отправляешь ту модель, что она требует, в БД кладешь то же самое, плюс `ownedByMe = true`. В холдере при отрисовке поста смотришь, если пост ownedByMe, то показываешь меню редактирования, если нет, то нет.

2023-12-11 14:53 UTC, tyupik requested changes

2023-12-11 14:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun removeAllPosts() =
Название не очень подходящее. Непонятно, откуда посты удаляются.

2023-12-11 14:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +            ownedByMe = if (it.authorId == auth.authStateFlow.value.id) true else false,
по-моему тут можно просто `ownedByMe = it.authorId == auth.authStateFlow.value.id`

2023-12-11 14:53 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +            ownedByMe = if (item.authorId == auth.authStateFlow.value.id) true else false,
и тут

2023-12-11 19:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/PostRepositoryImpl.kt
> +    override suspend fun removeAllPosts() =
Переименовал в removeAllDbPosts

2023-12-11 19:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +            ownedByMe = if (it.authorId == auth.authStateFlow.value.id) true else false,
переделал. 
Сейчас, вроде корректно отрабатывает. При старом методе были пропуски, когда значение ownedByMe проставлялось некорректно

2023-12-11 19:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/login/LoginRepositoryImpl.kt
> +        postRepository.updateLoginPostOwned(body.id)
переделал

2023-12-11 19:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +            ownedByMe = if (item.authorId == auth.authStateFlow.value.id) true else false,
переделал

2023-12-11 19:20 UTC, tyupik approved these changes

2023-12-11 19:23 UTC, merged