Add cicerone fragment navigation
WoodyMSK/SocialApp pull request #31
Opened 2024-01-29 21:53 UTC by WoodyMSK

2024-01-30 12:22 UTC, tyupik requested changes

2024-01-30 12:22 UTC, tyupik commented on app/build.gradle
> +    implementation("com.github.terrakok:cicerone:$cicerone_version")
скобки убери, чтобы одинаково было везде

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/NavigationModule.kt
> +    }
Так красивее будет. И ниже то же самое.

```suggestion
    fun provideRouter(): Router = cicerone.router
```

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/application/SocialApp.kt
> +        internal lateinit var INSTANCE: SocialApp
вроде не увидел, чтобы ты еще где-то использовал эту переменную, кроме как в этом файле. Зачем тогда `internal`? сделай приватной.

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/BottomNavigation.kt
> +interface BottomNavigation {
Если это интерфейс, то из названия файла это должно быть понятно. Добавь букву I в начало названия.
```suggestion
interface IBottomNavigation {
```

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +    private val navigator: com.github.terrakok.cicerone.Navigator =
сделай импорт

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/subnavigation/LocalCiceroneHolder.kt
> +class LocalCiceroneHolder {
а не надо здесь `@Inject constructor()`?

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +        for (f in fragments) {
давай без алфавитов, не есть хорошая практика
```suggestion
        for (fragment in fragments) {
```

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +            }
Вообще вот эту штуку хорошо бы вынести куда-нибудь в отдельный файл. Представь, что у тебя будет 100 экранов.

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +        for (f in fragments) {
```suggestion
        for (fragment in fragments) {
```

2024-01-30 12:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        const val CONTAINER_TAG_ARG = "CONTAINER_TAG"
```suggestion
        private const val CONTAINER_TAG_ARG = "CONTAINER_TAG"
```

2024-02-05 20:21 UTC, WoodyMSK commented on app/build.gradle
> +    implementation("com.github.terrakok:cicerone:$cicerone_version")
готово, убрал

2024-02-05 20:22 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/NavigationModule.kt
> +    }
исправил, внизу тоже

2024-02-05 20:23 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/application/SocialApp.kt
> +        internal lateinit var INSTANCE: SocialApp
исправил

2024-02-05 20:26 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/BottomNavigation.kt
> +interface BottomNavigation {
Исправил. 
Всегда стоит так называть файл, интерфейс или в каких-то определённых случаях?

2024-02-05 20:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +    private val navigator: com.github.terrakok.cicerone.Navigator =
Поправил

2024-02-05 20:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/subnavigation/LocalCiceroneHolder.kt
> +class LocalCiceroneHolder {
Вроде нет, мы сюда ни чего не инжектим, а так же нет ни каких аннотаций, как, например, в случае с viewModel, когда добавляем аннотацию @HiltViewModel. 
А если нужно было "@Inject constructor()", то компилятор бы ругался

2024-02-05 20:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +        for (f in fragments) {
тут назвал "f" из цикла (156 строка) как "activeFragment", потому что просто "fragment" вводится как переменная на 153 строке , На 158 строке мы потом присваиваем "fragment" = "activeFragment"

2024-02-05 20:43 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        const val CONTAINER_TAG_ARG = "CONTAINER_TAG"
добавил

2024-02-05 20:46 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        const val CONTAINER_TAG_ARG = "CONTAINER_TAG"
в другие фрагменты тоже

2024-02-06 11:10 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/BottomNavigation.kt
> +interface BottomNavigation {
В целом встречал 2 подхода: у некоторых интерфейсы просто называются, а  имплементация с `Impl` на конце. У нас в проекте интерфейс `IClassName`, а имплементация просто `ClassName`

2024-02-06 11:11 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/subnavigation/LocalCiceroneHolder.kt
> +class LocalCiceroneHolder {
Но ты ведь инжектишь этот класс куда-то? Не просто так он висит в воздухе. Если да, то нужны и аннотации и `@Inject conctructor()`

2024-02-06 11:12 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        const val CONTAINER_TAG_ARG = "CONTAINER_TAG"
Ага, только тебе надо как-то подумать, как от этого избавиться во всех фрагментах

2024-02-06 18:55 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/BottomNavigation.kt
> +interface BottomNavigation {
у меня просто интерфейсы репозиториев называются просто, а их имплементация с приставкой Impl

2024-02-06 19:06 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +        for (f in fragments) {
алфавит убрал, по нормальному назвал

2024-02-06 19:58 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/subnavigation/LocalCiceroneHolder.kt
> +class LocalCiceroneHolder {
Понял, добавил

2024-02-06 20:20 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +            }
решили пока оставить как есть

2024-02-06 20:44 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/navigation/BottomNavigation.kt
> +interface BottomNavigation {
решили оставить BottomNavigation

2024-02-18 15:33 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        const val CONTAINER_TAG_ARG = "CONTAINER_TAG"
Убрал их, ини особо ни в чём не участвовали

2024-02-22 21:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +    override fun onBackPressed() = viewModel.onBackPressed()
а где-то на ui эта кнопка есть? у тебя ведь нет тулбара, назад только системными кнопками или жестом.

2024-02-27 20:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +    override fun onBackPressed() = viewModel.onBackPressed()
это скорее для жестов. При свайпе назад из корневого фрагмента, такого как AuthFragment,  приложение сворачивается. Если убрать переопределение, то приложение сворачиваться не будет. 
Глянул как в VK, там приложение сворачивается, а в Тинькове нужно 2 раза свайпнуть, чтобы приложение свернулось

2024-03-31 22:06 UTC, tyupik requested changes

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +        }
этот код у тебя минимум 2 раза повторяется в этом классе

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +    private fun createScreenList() {
вроде хотели перенести это в Screens

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    lateinit var binding: FragmentLoginBinding
почему переменная перестала быть приватной?

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    override fun onBackPressed() = viewModel.onBackPressed()
зачем это здесь?

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginViewModel.kt
> +    fun onBackPressed() = router.backTo(authScreen())
здесь хватит обычного back. Ты на этот экран только с authScreen можешь попасть

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/my_profile/MyProfileScreenFragment.kt
> +    lateinit var binding: FragmentMyProfileBinding
и тут непонятно зачем убрал

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/new_post/NewPostViewModel.kt
> +    fun goToPostScreen() = router.backTo(postScreen())
достаточно back

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    lateinit var binding: FragmentRegistrationBinding
?

2024-03-31 22:06 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    fun onBackPressed() = router.backTo(authScreen())
back

2024-04-01 18:47 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +    private fun createScreenList() {
Перенёс. 
Да, точно. Нужно было оставить функцию, которая берет из мапы данные

2024-04-01 18:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    lateinit var binding: FragmentLoginBinding
брачок вышел. Вернул.

2024-04-01 18:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/my_profile/MyProfileScreenFragment.kt
> +    lateinit var binding: FragmentMyProfileBinding
вернул

2024-04-01 18:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationFragment.kt
> +    lateinit var binding: FragmentRegistrationBinding
вернул

2024-04-01 18:54 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    override fun onBackPressed() = viewModel.onBackPressed()
Да, тут пожалуй избыточно. 
Убрал

2024-04-01 18:59 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginViewModel.kt
> +    fun onBackPressed() = router.backTo(authScreen())
53 строку удалил. 
Базовый жест назад делает всё тоже самое

2024-04-01 19:35 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    override fun onBackPressed() = viewModel.onBackPressed()
Может вообще удалить тогда этот интерфейс BackButtonListener. Всё равно его где-то добавляю, а где-то нет

2024-04-01 19:37 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginViewModel.kt
> +    fun onBackPressed() = router.backTo(authScreen())
сделал router.exit() на 53 строке

2024-04-01 19:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/new_post/NewPostViewModel.kt
> +    fun goToPostScreen() = router.backTo(postScreen())
Сделал router.exit().
Оставил только:
fun onBackPressed() = router.exit()

2024-04-01 19:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/registration/RegistrationViewModel.kt
> +    fun onBackPressed() = router.backTo(authScreen())
Сделал router.exit()

2024-04-01 19:42 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/login/LoginFragment.kt
> +    override fun onBackPressed() = viewModel.onBackPressed()
в RegistrationFragment тоже убрал 
override fun onBackPressed() = viewModel.onBackPressed()

2024-04-01 19:43 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/activity/MainActivity.kt
> +        }
этого уже нету в MainActivity

2024-04-02 16:27 UTC, tyupik approved these changes

2024-04-02 16:27 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/Screens.kt
> +    fun createScreenList() {
может сделать приватной функцией и просто в init засунуть? а не вызывать извне

2024-04-02 19:20 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/Screens.kt
> +    fun createScreenList() {
сделал

2024-04-02 19:21 UTC, merged