Migration of Profile fragment from xml to Compose
WoodyMSK/SocialApp pull request #35
Opened 2024-06-20 21:27 UTC by WoodyMSK

2024-06-22 10:22 UTC, tyupik requested changes

2024-06-22 10:22 UTC, tyupik commented on app/build.gradle
> +    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
у тебя же нет тестов

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/api/ProfileService.kt
> +    suspend fun getMyProfileData(
убери `My`. Это же просто ProfileService, его можно использовать для любого профиля.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/profile/ProfileRepositoryImpl.kt
> +    lateinit var auth: AppAuth
а в конструктор нельзя заинжектить это?

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/profile/ProfileRepositoryImpl.kt
> +            return@withContextIO response.body().throwAppError(response)
у тебя где-то есть return, где-то нет. Придерживайся одного стиля хотя бы в пределах одного файла.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/profile/ProfileRepository.kt
> +    suspend fun logout()
У тебя же уже был где-то метод с логаутом?
Надо отдельно интерактор, где будут все методы авторизации: регистрация, авторизация, логаут. И потом уже этот интерактор инжектить везде, где надо.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/profile/model/User.kt
> +    val id: Int = 0,
зачем дефолтные значения для id, login, name? это ведь обязательные поля для любого юзера

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/compose/CommonFunctions.kt
> +fun LoadAvatar(url: String) {
а что тут будет, пока аватарка грузится?

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/new_post/NewPostFragment.kt
> +        if (this::post.isInitialized) {
можно без `this`, будет работать

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                onNewPostClick(Bundle())
получается, ты всегда создаешь бандл и кладешь его, когда переходишь на экран с новым постом. Зачем тратить ресурсы, если это не редактирование, а просто создание? Нужен нулабельный бандл.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/ProfileScreenFragment.kt
> +                CustomTheme {
Название поменяй, а то что за кастомная тема? непонятно.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/ProfileViewModel.kt
> +    private fun checkAuth(): Boolean = if (auth.authStateFlow.value.id == 0) false else true
у тебя функция возвращает boolean, почему она называется checkAuth? по названию вообще не разобрать, что она вернет тебе. Подбери подходящее название.
И какаая-то сложная функция получилась. Можно ведь оставить только то, что в скобках.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                        ) {
что-то со скобками странное происходит. Плавают.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                    mutableStateOf(if (post.content.length > 200) false else true)
опять что-то сложное, можно ведь просто `mutableStateOf(post.content.length <= 200)`

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                            if (post.attachment != null && post.attachment.type == AttachmentType.IMAGE) {
Первое услови избыточное. Если второе выполняется, то первое тем более.

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                                            painterResource(id = R.drawable.ic_like_filled_24dp)
`painterResource` вынеси перед `If`

2024-06-22 10:22 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/theme/Theme.kt
> +        if (!darkTheme) {
! лучше использовать поменьше. Ведь лучше читается:
```
if (darkTheme) {
            DarkColorScheme
        } else {
            LightColorScheme
        }
```

2024-06-22 11:37 UTC, WoodyMSK commented on app/build.gradle
> +    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
ага, убрал

2024-06-22 11:41 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/api/ProfileService.kt
> +    suspend fun getMyProfileData(
постарался везде убрать "my", но тут проморгал. 
Ещё здесь же переименовал getMyPostList в getProfilePostList. так информативней, вроде.

2024-06-22 11:48 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/profile/ProfileRepositoryImpl.kt
> +    lateinit var auth: AppAuth
да, лучше в конструктор

2024-06-22 11:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/profile/ProfileRepositoryImpl.kt
> +            return@withContextIO response.body().throwAppError(response)
Хорошо. Убрал return

2024-06-22 12:04 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/compose/CommonFunctions.kt
> +fun LoadAvatar(url: String) {
не хотел добавлять индикатор загрузки, но плейсхолдер всё же стоит добавить - добавил.
Ещё изменил картинку при ошибке, чтобы не повторялись.

2024-06-22 12:07 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/new_post/NewPostFragment.kt
> +        if (this::post.isInitialized) {
ага, пасиб. С this для меня по-читабельнее

2024-06-22 12:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +                onNewPostClick(Bundle())
переделал на нулабельный бандл

2024-06-22 12:58 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/ProfileScreenFragment.kt
> +                CustomTheme {
поменял на SocialAppTheme

2024-06-22 13:18 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/ProfileViewModel.kt
> +    private fun checkAuth(): Boolean = if (auth.authStateFlow.value.id == 0) false else true
Для функций, которые возвращают Boolean, обычно вначале имени добавляют "is"

2024-06-22 13:26 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                    mutableStateOf(if (post.content.length > 200) false else true)
Убрал избыточность

2024-06-22 13:28 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                        ) {
ураган подраскидал ))
Отрефакторил

2024-06-22 13:31 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                            if (post.attachment != null && post.attachment.type == AttachmentType.IMAGE) {
пожалуй так и есть, укоротил.

2024-06-22 13:37 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                                            painterResource(id = R.drawable.ic_like_filled_24dp)
Сделал

2024-06-22 13:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/theme/Theme.kt
> +        if (!darkTheme) {
Да, так лучше, исправил

2024-06-22 17:23 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/profile/model/User.kt
> +    val id: Int = 0,
Убрал. В чистом виде User() ни где не применяется

2024-06-22 17:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/profile/ProfileRepository.kt
> +    suspend fun logout()
Договорились сделать отдельный Auth interactor в отдельной задаче

2024-06-25 09:07 UTC, tyupik requested changes

2024-06-25 09:07 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/new_post/NewPostFragment.kt
> +        savedInstanceState?.getSerializable(REQ_POST_KEY) ?:
`?:` перенеси на другую строку, чтобы наглядно был

2024-06-25 09:07 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +            if (viewModel.isAuth()) run{
после `run` пробела не хватает, по-моему

2024-06-25 09:07 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +    private val bundle = Bundle()
а зачем ты здесь создаешь бандл? Почему нельзя его создавать сразу в `onEdit`, а оттуда передавать, куда нужно.

2024-06-25 09:07 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/ProfileViewModel.kt
> +        viewModelScope.launch() {
а если ошибка?

2024-06-25 20:02 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/new_post/NewPostFragment.kt
> +        savedInstanceState?.getSerializable(REQ_POST_KEY) ?:
готово

2024-06-25 20:04 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +            if (viewModel.isAuth()) run{
пробел добавил, мне так больше нравится, автокоррекция его не убрала

2024-06-25 20:08 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/post/PostScreenFragment.kt
> +    private val bundle = Bundle()
сделал создание бандла при клике, в профиле тоже

2024-06-25 20:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/ProfileViewModel.kt
> +        viewModelScope.launch() {
Сделал exceptionHandler, чёт я затупил, что сразу не сделал

2024-06-25 21:40 UTC, tyupik approved these changes

2024-06-26 20:16 UTC, merged