Dependency injection migration from Hilt to Dagger2
WoodyMSK/SocialApp pull request #36
Opened 2024-07-13 14:26 UTC by WoodyMSK

2024-07-15 11:34 UTC, tyupik requested changes

2024-07-15 11:34 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/RepositoryModule.kt
> +interface RepositoryModule {
вообще на будущее учти, я тебе уже говорил, что в больших проектах надо каждый экран в отдельный модуль выносить, а то у тебя тут сразу все репозитории в даггере прописываются. Должно по мере необходимости все это быть. Тут тетбе кастомные скоупы помогут как раз.

2024-07-15 11:34 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        viewModel = ViewModelProvider(this, viewModelFactory).get(AuthViewModel::class.java)
Подумай, можно ли как-нибудь вынести все это в отдельное место. Может, в модуле возвращаемый тип какой-нибудь, у которого будет метод с вот этой всей фигней. Потому что каждый раз в каждом фрагменте все это писать - такое себе, мне кажется, надо как-то упростить код. Ход мыслей ты понял, надеюсь)
Я пока глубоко не думал, но вот я как заказчик хочу видеть красивее.

2024-07-15 20:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/auth/AuthFragment.kt
> +        viewModel = ViewModelProvider(this, viewModelFactory).get(AuthViewModel::class.java)
переделал, теперь красивее

2024-07-16 11:19 UTC, tyupik approved these changes

2024-07-16 19:22 UTC, merged