Add remove post dialog for profile screen
WoodyMSK/SocialApp pull request #37
Opened 2024-11-03 15:52 UTC by WoodyMSK

2024-11-03 18:42 UTC, tyupik requested changes

2024-11-03 18:42 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                    onDelete(postId.toString())
у тебя то `remove`, то `delete`, приди к чему-то одному) 
delete более правильно будет

2024-11-03 18:42 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/RemoveItemDialog.kt
> +    onNoClick: () -> Unit,
Вообще можно одну функцию передавать, мне кажется, и передавать в нее Boolean.
Что-то типа `onClick: (Boolean) -> Unit,`

2024-11-04 14:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                    onDelete(postId.toString())
Переименовал

2024-11-04 14:14 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/RemoveItemDialog.kt
> +    onNoClick: () -> Unit,
переделал на onClick: (Boolean) -> Unit

2024-11-04 14:50 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/profile/compose/Profile.kt
> +                    }
```suggestion
                    if (it) onDelete(postId.toString())
```

2024-11-04 14:50 UTC, tyupik approved these changes

2024-11-04 15:29 UTC, merged