Refactor event screen from xml to compose
WoodyMSK/SocialApp pull request #38
Opened 2024-12-01 17:50 UTC by WoodyMSK

2024-12-01 18:10 UTC, WoodyMSK commented
Экран ивентов верстал по макету фигмы:
https://www.figma.com/design/8z1sV6KIf6Sc1y02TrY2XS/Nmedia?node-id=13-2277&node-type=frame&t=D6cbZ1pCAZcRcVBy-0

Старался делать по шаблону. Но не ставил цвета шрифтов и фоновые цвета подбирал примерно такие же как в макете, но из MaterialTheme - это чтобы тёмная тема норм отрабатывала

2024-12-01 19:15 UTC, tyupik requested changes

2024-12-01 19:15 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            participants = it.participantsIds.orEmpty().size,
будто бы нет смысла в этом. Лучше использовать одну переменную `participants`, которая будет массивом, а дальше брать из нее просто `size`. Так красивее, меньше кода и правильнее.

2024-12-01 19:15 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +                    .header("Api-Key", "c1378193-bc0e-42c8-a502-b8d66d189617")
удоли

2024-12-01 19:15 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                            fontSize = 16.sp
Кажется, что нужно где-то вынести стили или отдельный компонент, потому что все это у тебя будет дублироваться как минимум на постах еще. И писать там то же самое - не комильфо.
И для другого `Text` то же самое

2024-12-01 19:15 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                DropdownMenu(
Нужна проверка на `authorId`, а то у всех отображается.

2024-12-01 19:15 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                        Text(
Добавь над каждым элекментом комментарий, для чего он нужен: лайки, шаринг, описание, картинка и т.д., а то экран большой, много элементов и не понять быстро, что к чему относится.

2024-12-01 19:15 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                            onClick = { }
тудушки добавь, чтобы было видно, что надо доделать. 
На шаринге тоже

2024-12-02 20:21 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> +            participants = it.participantsIds.orEmpty().size,
Сделал. 
Ток название оставил participantsIds, как оно в бэка приходит, чтобы не было диссонанса

2024-12-02 20:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                DropdownMenu(
добавил. 
Оставлял чисто чтобы можно было глянуть как выглядит кнопка

2024-12-05 19:26 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                        Text(
добавил описание

2024-12-05 19:35 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                            onClick = { }
добавил

2024-12-05 21:18 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +                    .header("Api-Key", "c1378193-bc0e-42c8-a502-b8d66d189617")
Удалил

2024-12-05 21:19 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                            fontSize = 16.sp
Вынес отдельно стили текста

2024-12-06 10:24 UTC, tyupik requested changes

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> -    fun mapToDto(items: List<EventDAO>): List<EventDTO> = items.map {
а это чего убрал? не нужно?

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/event/mapper/EventMapper.kt
> -    fun mapEventToDao(items: List<Event>): List<EventDAO> = items.map {
и тут

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +    Card(
а точно надо весь экран оборачивать в `Card`?

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Row(
такое ощущение, что один `Row` тут лишний. Перепроверь.

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            // context menu button
Мне кажется, лучше перед всем эти проверять на `isMenuVisibility`. А то получается, что ты уже как минимум лиший `Column` создаешь, если меню не  будет.
```
if (isMenuVisibility) {
    Column...
}
```

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                        Surface {
а зачем тут `Surface`? Ты же ничего не делаешь с ним, он у тебя просто как пустой контейнер.

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Column(
тут снова куча вложенностей какая-то. Надо пересмотреть весь экран, мне кажется, тут можно сильно меньше сделать всего.

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Row {
Зачем тут `Row`, в котором лежит только один текст?

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Column {
Зачем?

2024-12-06 10:24 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                    Row(
![image](https://github.com/user-attachments/assets/beefa9a9-4659-40dc-ba25-fcbfdd16f296)

2024-12-07 18:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/event/mapper/EventMapper.kt
> -    fun mapToDto(items: List<EventDAO>): List<EventDTO> = items.map {
да, не используется

2024-12-07 18:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/event/mapper/EventMapper.kt
> -    fun mapEventToDao(items: List<Event>): List<EventDAO> = items.map {
да, тут тоже не используется

2024-12-07 18:44 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +    Card(
убрал, вроде, всё норм

2024-12-07 19:11 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Row(
Тут используются два Row, чтобы использовать две разные компоновки элементов внутри этих Row. Для того, чтобы Аватарка, имя и дата были в левой стороне экрана, а копка контекстного меню была в правой части. 

![image](https://github.com/user-attachments/assets/b8d62f6b-1052-4246-8fc0-d69b3f3cbb96)

2024-12-07 19:19 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            // context menu button
Да, точно. 
Поменял местами AnimatedVisibility и Column (обернул Column в AnimatedVisibility). По идее должно быть всё ровно

2024-12-07 19:21 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                        Surface {
в принципе верно - убрал

2024-12-07 20:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Column {
Убрал. он тут не нужен

2024-12-07 20:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Column(
Убрал, который с размерами, в принципе он ни чего не даёт.

2024-12-07 20:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Row {
Убрал

2024-12-07 21:17 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                    Row(
Проверил. Вроде всё ровно.
Тут используются два Row, чтобы использовать две разные компоновки элементов внутри этих Row. Для того, чтобы лайки и share были в левой стороне экрана, а участники ивента были в правой части.
Третий Row чтобы объединить кнопку лайков и счётчик лайков. 

![image](https://github.com/user-attachments/assets/81000a4b-00c9-4eaf-a6e5-065f55e10e75)

2024-12-08 10:31 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Column(
Пересмотрел весь экран снова, где решения показались сомнительными - переделал

2024-12-08 10:54 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                .padding(top = 32.dp),
Перенёс отсюда нижний паддинг в блок лайков, share и т.д., потому что кнопка "...читать дальше" уползала на расстояние этого паддинга от описания ивента.

2024-12-08 10:57 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                        modifier = Modifier.size(width = 22.dp, height = 18.dp),
Заменил IconButton на Box, потому что смысла особо в нём не нашёл. Обработку нажатия можно добавить и к Image

2024-12-08 10:58 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                                    modifier = Modifier.size(width = 22.dp, height = 18.dp),
Заменил IconButton на Box, потому что смысла особо в нём не нашёл. Обработку нажатия можно добавить и к Image

2024-12-08 10:59 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Box(
Обернул весь Box в event.type?.name?.let { }

2024-12-12 21:12 UTC, WoodyMSK commented
[app-release.zip](https://github.com/user-attachments/files/18117497/app-release.zip)

2024-12-13 09:45 UTC, tyupik requested changes

2024-12-13 09:45 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +            val isMenuVisibility = remember { MutableTransitionState(true) }
не вижу, где изменяется поле. Всегда `true` что ли?

2024-12-13 09:45 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Text(
лайки ты обернул в бокс, а здесь нет. Тут ведь тоже может прыгать. Единое надо что-то

2024-12-13 19:11 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +            val isMenuVisibility = remember { MutableTransitionState(true) }
Починил.
Когда тестил, забыл вернуть

2024-12-13 19:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event/compose/EventScreen.kt
> +                            Text(
да, упустил. Добавил Box

2024-12-16 21:05 UTC, WoodyMSK commented
Замечание: Я не авторизован, а у меня есть плюсик. 
Исправлено

2024-12-29 21:25 UTC, WoodyMSK commented
Лоадер в углу

2024-12-29 21:27 UTC, WoodyMSK commented
Я не авторизован, а у меня есть плюсик

2024-12-29 21:27 UTC, WoodyMSK commented
Не нравится мне, как выглядит "читать далее". Думаю, нада добавлять в текущему тексту annotated string и делать его кликабкльным, а не новый текст на новой строке

2024-12-29 21:28 UTC, WoodyMSK commented
Картинки слева

2025-01-09 14:59 UTC, tyupik approved these changes

2025-01-09 14:59 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/compose/CommonFunctions.kt
> +                color = Color(0xFF6750A4),
Несколько раз встречается этот цвет, вынеси в переменную

2025-01-09 21:39 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/common/compose/CommonFunctions.kt
> +                color = Color(0xFF6750A4),
Сделал.

Не очень быстро получилось. Пришлось из переменной, содержащей стили (val typography) сделать Composable
fun typography()

2025-01-09 21:43 UTC, merged