added post view model, post adapter, post repository, post mock data,…
WoodyMSK/SocialApp pull request #4
Opened 2023-07-22 12:17 UTC by WoodyMSK

added post view model, post adapter, post repository, post mock data, models, event view model, event adapter, event repository, event mock data.

2023-07-22 13:01 UTC, tyupik requested changes

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/model/Coords.kt
> +    val long: String
Стараяйся в дата классах на последней переменной в конце тоже ставить запятую. Пример: ты захочешь добавить какое-то новое поле, придется добавить запятую, в гите отобразится так, что эту строчку ты тоже изменил - лишняя информация.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventAdapter.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
Что делает эта аннотация?

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventRepository.kt
> +    suspend fun getAllEventsFromRepository()
Такие вещи старайся разделять строкой. Красивее выглядеть будет и читабельнее.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventRepository.kt
Как у тебя репозиторий окакзался в UI слое?
Почитай про чистую архитекруту, разделяй хотя бы примерно, как в ней заложено.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventRepository.kt
> +    suspend fun getAllEventsFromRepository()
`FromRepository` не нужно. Ты и так будешь вызывать это через репозиторий ведь. Будет что-то типа `repository.getEventList()`

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewHolder.kt
> +private val eventDateFormat: DateTimeFormatter = DateTimeFormatter.ISO_DATE_TIME
Не надо держать это здесь. Тебе наверняка понадобится это еще в другом месте (например, на событиях).
Сделай где-нибудь файл `Utils.kt` и положи туда.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewHolder.kt
> +                    .into(binding.ivCardEventAuthorAvatar)
Как ты можешь заметить, этот код у тебя повторяется несколько раз. Даже в этом файле как минимум 2 раза.
В `Utils`  необходимо сделать экстеншн для `ImageView`, назвать его `load`, передавать в него `url`.
Тогда здесь у тебя будет все красиво: `ivCardEventAuthorAvatar.load(url = event.authorAvatar)`.
Глайд у тебя присутствовать должен желательно только там. В других местах прям по необходимости.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewHolder.kt
> +            if (event.attachment != null && event.attachment.type == "IMAGE") {
Никаких строк в коде. В данном случае надо сделать `enum` класс, в котором будут перечислены все виды вложений.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewModel.kt
> +class EventViewModel(application: Application) : AndroidViewModel(application) {
сюда точно нужен Application класс? Что-то мне не нравится, что он здесь присутствует.

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostRepository.kt
> +    suspend fun getAllPostsFromRepository()
нейминг

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostRepository.kt
Не в UI слое должен быть

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostScreenFragment.kt
> +    private val viewModel: PostViewModel by activityViewModels()
точно `activityViewModels()`?

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostViewHolder.kt
> +                    .into(binding.ivCardPostAuthorAvatar)
см. выше

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostViewHolder.kt
> +            if (post.attachment != null && post.attachment.type == "IMAGE") {
см. выше

2023-07-22 13:01 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostViewModel.kt
> +    private val postRepository: PostRepository = PostRepositoryImpl()
Вот это вообще нехорошо. Нужно подключать DI обязательно.

2023-07-23 09:17 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/model/Coords.kt
> +    val long: String
принято. Добавил

2023-07-23 09:55 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventAdapter.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
эта аннотация @RequiresApi(Build.VERSION_CODES.*api_code*) просилась, когда я добавлял форматирование даты. Сейчас же с новым методом    она не просится - удалил. 

В интернетах пишут, что аннотированный элемент должен вызываться только на заданном уровне API (*api_code*) или выше. Аннотированный элемент ниже заданного уровня API не будет вызываться

2023-07-23 09:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventRepository.kt
> +    suspend fun getAllEventsFromRepository()
Принято. Исправил

2023-07-23 10:02 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventRepository.kt
> +    suspend fun getAllEventsFromRepository()
понял - избыточно. Переименовал в "getAllEventList()" т.к. функция запрашивает именно полный список ивентов, по API возможны ещё и другие варианты

2023-07-23 10:19 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewHolder.kt
> +private val eventDateFormat: DateTimeFormatter = DateTimeFormatter.ISO_DATE_TIME
сделано

2023-07-23 10:47 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewHolder.kt
> +                    .into(binding.ivCardEventAuthorAvatar)
Добавил в Utils.kt два метода "load" и "loadCircleCrop" для картинок и аватарок соответственно. 
Для применения к IV картинок из drawable, применил метод setImageResource()

2023-07-23 11:05 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewHolder.kt
> +            if (event.attachment != null && event.attachment.type == "IMAGE") {
сделал enum для IMAGE. Остальные пока не используются - их не добавлял

2023-07-23 11:25 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventViewModel.kt
> +class EventViewModel(application: Application) : AndroidViewModel(application) {
Переделал на ViewModel. 
В интернетах пишут, что AndroidViewModel содержит контекст приложения, его лучше не использовать, где это не требуется из-за усложнения приложения, если кратко.

2023-07-23 11:29 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostRepository.kt
> +    suspend fun getAllPostsFromRepository()
Переделал на getAllPostList()

2023-07-23 11:30 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostScreenFragment.kt
> +    private val viewModel: PostViewModel by activityViewModels()
Переделал на viewModels()

2023-07-23 11:32 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostViewHolder.kt
> +            if (post.attachment != null && post.attachment.type == "IMAGE") {
Добавил экстеншены "load" и "loadCircleCrop" для картинок и аватарок соответственно. И enum IMAGE

2023-07-23 15:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostViewModel.kt
> +    private val postRepository: PostRepository = PostRepositoryImpl()
сделал при помощи кирки, лопаты и еще какой-то матери (c)

2023-07-23 15:44 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostViewHolder.kt
> +                    .into(binding.ivCardPostAuthorAvatar)
Добавил экстеншен "load", где можно передать параметр, в зависимости от которого применится функция circleCrop()

2023-07-25 07:44 UTC, tyupik requested changes

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/ui/event_screen/EventRepositoryImpl.kt
А зачем каталог `ui` здесь нужен? Убирай.

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/ui/event_screen/EventRepositoryImpl.kt
> +val mockEvents = listOf(
Такие вещи всегда приватными делай лучше, вдруг кому-то в реальном проекте взбрендит в голову достать отсюда напрямую

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +import java.util.*
*

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +}
Здесь оставляешь просто:
```
fun ImageView.load(
    url: String,
    vararg transforms: BitmapTransformation = emptyArray()
) {
    Glide.with(this)
        .load(url)
        .placeholder(R.drawable.ic_downloading_24)
        .error(R.drawable.ic_error_24)
        .timeout(5_000)
        .transform(*transforms)
        .into(this)
}
```

При вызове load() будет вот так на примере аватарки:
```
ivCardEventAuthorAvatar.load(
    url = event.authorAvatar,
    transforms = arrayOf(CircleCrop())
)
```

В `transforms` ты можешь положить нужные трансформации, в том числе и кроп. Если он нужен, то кладешь, нет - нет.

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/enumeration/AttachmentType.kt
Сразу лучше добавляй DAO это или DTO

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/enumeration/AttachmentType.kt
> +package ru.woodymsk.socialapp.domain.enumeration
Не нужен пакет `enumeration`, просто положи в `model`

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/ui/event_screen/EventRepositoryModule.kt
> +package ru.woodymsk.socialapp.domain.ui.event_screen
`di` лучше отдельно положить: `ru.woodymsk.socialapp.di`

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventAdapter.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
?

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventScreenFragment.kt
> +package ru.woodymsk.socialapp.presentation.ui.event_screen
здесь пакет `ui` тоже не нужен. У тебя и так слой `presentation`, все понятно ведь.

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventViewHolder.kt
> +                ivCardEventPicture.load(event.attachment.url, false)
Что значит вторым параметром false? Я не смогу догадаться, не провалившись в функцию. Когда больше одного параметра, нужно писать их имена.

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventViewModel.kt
> +    private val eventRepository: EventRepositoryImpl
А почему у тебя тут оказался `RepositoryImpl`? Он в каком слое лежит и в каком слое `ViewModel`?
Как поймешь ошибку, напиши мне, я скажу, как должно быть правильно.

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventViewModel.kt
> +    val events: LiveData<List<EventsItem>> = eventRepository.events
Я бы, конечно, сделал по-другому. 
Так у тебя получается 2 лайвдаты: одна из репозитория во вьюмодель, вторая из вьюмодели во фрагмент.
Я бы лучше из репозитория доставал просто список элементов, а во вьюмодели клал уже в лайвдату.

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/post_screen/PostAdapter.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
?

2023-07-25 07:44 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/post_screen/PostViewHolder.kt
> +            bCardPostLike.text = "${post.likeOwnerIds.size}"
А если будет ноль?

2023-07-25 07:44 UTC, tyupik commented on app/src/main/res/layout/item_card_event.xml
> +            android:paddingHorizontal="32dp"
почему везде по 32 стало? Глянь, как это выглядит)

2023-07-25 19:12 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/ui/event_screen/EventRepositoryImpl.kt
пакет ui убрал. 
Хотелось, чтобы все папки "..._screen" лежали в какой-то одной.

2023-07-25 19:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/ui/event_screen/EventRepositoryImpl.kt
> +val mockEvents = listOf(
Принято. исправил.

2023-07-25 19:18 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +import java.util.*
Виноват, исправил

2023-07-25 19:26 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +}
о, спасибо. Буду знать. Исправил.

2023-07-25 19:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/enumeration/AttachmentType.kt
Переименовал в AttachmentTypeDAO

2023-07-25 19:51 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/enumeration/AttachmentType.kt
> +package ru.woodymsk.socialapp.domain.enumeration
готово

2023-07-25 19:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/ui/event_screen/EventRepositoryModule.kt
> +package ru.woodymsk.socialapp.domain.ui.event_screen
сделал

2023-07-25 19:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventAdapter.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
упс, это лишнее - убрал.

2023-07-25 19:59 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventScreenFragment.kt
> +package ru.woodymsk.socialapp.presentation.ui.event_screen
хорошо, исправил

2023-07-25 20:01 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/event_screen/EventRepository.kt
Сделал как обговорили:
presentation слой: фрагмент и вьюмодель
Домен слой: интеракторы, мапперы дто на дао, интерфейс репозитория, дао модели
Дата слой: имплементация репозитория, рум, ретрофит, дто модели

2023-07-25 20:01 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/ui/post_screen/PostRepository.kt
Сделал как обговорили:
presentation слой: фрагмент и вьюмодель
Домен слой: интеракторы, мапперы дто на дао, интерфейс репозитория, дао модели
Дата слой: имплементация репозитория, рум, ретрофит, дто модели

2023-07-25 20:04 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventViewHolder.kt
> +                ivCardEventPicture.load(event.attachment.url, false)
Понял, учту в дальнейшем

2023-07-25 20:09 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventViewModel.kt
> +    private val eventRepository: EventRepositoryImpl
Нужно наследоваться от ...Repository, иначе мы через слой прыгаем, пропуская data

2023-07-25 20:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/event_screen/EventViewModel.kt
> +    val events: LiveData<List<EventsItem>> = eventRepository.events
Можно и так, переделал. 
Но ток чёт у меня не оч красивая функция loadAllEvents() получается. 

@HiltViewModel
class EventViewModel @Inject constructor(
    private val eventRepository: EventRepository
) : ViewModel() {

    private val _events = MutableLiveData<List<EventsItem>>()
    val events: LiveData<List<EventsItem>>
        get() = _events

    init {
        loadAllEvents()
    }

    private fun loadAllEvents() = viewModelScope.launch {
        eventRepository.getAllEventList()
        _events.value = eventRepository.events
    }
}

2023-07-25 21:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/post_screen/PostAdapter.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
упс, это лишнее - убрал.

2023-07-25 21:48 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/presentation/ui/post_screen/PostViewHolder.kt
> +            bCardPostLike.text = "${post.likeOwnerIds.size}"
сделал, как обговорили. Только использовал функцию isNotEmpty. Как я понял, isNotBlanck для символов, а там List

2023-07-25 21:50 UTC, WoodyMSK commented on app/src/main/res/layout/item_card_event.xml
> +            android:paddingHorizontal="32dp"
поправил, теперь ровно

2023-07-26 09:18 UTC, tyupik commented
Необходимо поправить UI: элемента попадают под навбар

2023-07-29 11:34 UTC, tyupik requested changes

2023-07-29 11:34 UTC, tyupik commented on app/src/main/res/values/dimens.xml
> +    <dimen name="image_view_high">400dp</dimen>
Во-первых, `height` с опечаткой написал, во-вторых, непонятен контекст: что за image, где она и зачем. Лучше назвать как-нибудь типа `attachment_image_height`

2023-07-29 11:34 UTC, tyupik commented on app/src/main/res/values/strings.xml
> +    <string name="participantsCounts">Количество участников:</string>
никакого CamelCase в названих ресурсов
И выше поправь, я, видимо, пропустил.

2023-07-29 11:34 UTC, tyupik commented on app/src/main/res/layout/item_card_post.xml
> +            android:layout_height="@dimen/image_view_high"
Давай зедсь все-таки немного по-другому сделаем. Высоту оставим `wrap_content`. Также добавь строчку `android:adjustViewBounds="true"`, можешь погуглить, что она делает.
Правда при таком раскладе возможен вариант появления очень длинной картинки. Но давай условимся, что такую картинку нельзя будет згрузить, бэк этого не даст, поэтому тут у нас все будет ок.

Если оставить все так, как есть у тебя, то условно получается картинка размером (ширина экрана х 400 dp), и ты все картинки вписываешь в этот прямоугольник. По итогу широкие картинки будут сплюснутые. Либо если их кропнуть, то сильно обрезанные.

В ивентах то же самое сделай.

2023-07-29 11:34 UTC, tyupik commented on app/src/main/res/layout/item_card_post.xml
> +            android:scaleType="fitXY"
эта строчка лишняя, если сделать то, что я описал выше.

2023-07-29 11:34 UTC, tyupik commented on gradle.properties
> +android.nonFinalResIds=false
ты знаешь, что все это значит? Я нет. Можешь объяснить мне)

2023-07-29 11:34 UTC, tyupik commented on .idea/compiler.xml
Зачем тебе вообще файлы из папки .idea в гите? Внести папку в гитигнор, чтобы сюда не заливалось ничего такого.

2023-07-29 11:34 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +
лишняя строка

2023-07-29 11:34 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +        .placeholder(ic_downloading_24)
Предлагаю переделать плейсхолдер на нормальный с анимацией:
```
fun ImageView.load(
    url: String,
    vararg transforms: BitmapTransformation = emptyArray()
) {
    val circularProgressDrawable = CircularProgressDrawable(context)
    circularProgressDrawable.strokeWidth = 5f
    circularProgressDrawable.centerRadius = 30f
    circularProgressDrawable.start()

    Glide.with(this)
        .load(url)
        .placeholder(circularProgressDrawable)
        .error(ic_error_24)
        .timeout(5_000)
        .transform(*transforms)
        .into(this)
}
```

2023-07-29 19:09 UTC, WoodyMSK commented on app/src/main/res/values/dimens.xml
> +    <dimen name="image_view_high">400dp</dimen>
понял, сделал

2023-07-29 19:12 UTC, WoodyMSK commented on app/src/main/res/values/strings.xml
> +    <string name="participantsCounts">Количество участников:</string>
готово

2023-07-29 19:16 UTC, WoodyMSK commented on app/src/main/res/layout/item_card_post.xml
> +            android:layout_height="@dimen/image_view_high"
сделал. Так действительно лучше

2023-07-29 19:17 UTC, WoodyMSK commented on app/src/main/res/layout/item_card_post.xml
> +            android:scaleType="fitXY"
убрал

2023-07-29 19:28 UTC, WoodyMSK commented on gradle.properties
> +android.nonFinalResIds=false
Я подозреваю, что эта штука появилась после обновления Студии или обновления AGP 8.0. Точлком не понял, что это но пишут, что это может влиять на неверное извлечение ресурсов. 
https://www.solveforum.com/forums/threads/solved-android-nonfinalresids-false-causes-incorrect-resource-retrieving-with-the-obfuscation-enabled.2801791/
https://question-it.com/questions/19670993/problema-obfuskatsii-android-pri-perehode-na-android-gradle-plugin-agp-80-i-java-17

хз оставить или нет

2023-07-29 19:40 UTC, WoodyMSK commented on .idea/compiler.xml
внёс
/.idea/

2023-07-29 19:43 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +
без них подсвечивает красным строки
    inputFormat.timeZone = **TimeZone**.getTimeZone("UTC")

        return outputFormat.format(date as **Date**)

2023-07-29 19:46 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +
убрал

2023-07-29 19:48 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +        .placeholder(ic_downloading_24)
да, так круто

2023-07-29 21:52 UTC, tyupik approved these changes

2023-07-29 21:52 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/presentation/event_screen/EventViewHolder.kt
> +            } else bCardEventMoreContentText.isGone = true
Если ты в if поставил скобки, то в else тоже нужно ставить, даже если там одна строчка.

Второе: isVisible и isGone - это противоположные значения. Лучше использовать что-то одно для читаемости.
Лучше `isVisible = true` или `isVisible = false`

2023-07-29 21:52 UTC, tyupik commented on app/src/main/res/values/strings.xml
> +    <string name="places_work">места работы</string>
работа в понимании места заработка - это job. Так что тут `job_places`

2023-07-29 21:54 UTC, merged