add retrofit
WoodyMSK/SocialApp pull request #6
Opened 2023-07-30 12:50 UTC by WoodyMSK

2023-07-30 14:55 UTC, tyupik requested changes

2023-07-30 14:55 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    }
Вот этого не должно быть в модуле, а тем более ты не должен создавать тут ретрофит и okhttp билдер. По идее у тебя должен быть в дата слое файл, в котором okHttp и клиент ретрофита. А здесь в модуле ты только провайдишь тот файл из дата слоя и все.
Вся информация о серверах, как скачивать файлы и т.д. должна быть только в дата слое.

2023-07-31 18:51 UTC, tyupik requested changes

2023-07-31 18:51 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +        .build()
Давай так:
```

fun provideOkhttp(): OkHttpClient {

    val logging = HttpLoggingInterceptor().apply {
        if (BuildConfig.DEBUG) {
            level = HttpLoggingInterceptor.Level.BODY
        }
    }

   return OkHttpClient.Builder()
        .addInterceptor(logging)
        .build()
}
```

2023-07-31 18:51 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    }
Это убери отсюда

2023-07-31 18:51 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    }
Это тоже убрать можно

2023-07-31 18:51 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +        .baseUrl(BASE_URL)
```suggestion
        .baseUrl(BuildConfig.BASE_URL)
```

2023-07-31 18:54 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/api/ApiService.kt
> +interface ApiService {
А тут уточнить надо какой сервис: посты, ивенты, профиль, регистрация и т.д.
Все в один пихать не надо

2023-07-31 19:09 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +        .build()
сделал

2023-07-31 19:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    }
удалил

2023-07-31 19:10 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/di/ApiModule.kt
> +    }
удалил

2023-07-31 20:00 UTC, tyupik approved these changes

2023-07-31 20:00 UTC, merged