add post business logic
WoodyMSK/SocialApp pull request #9
Opened 2023-08-03 04:37 UTC by WoodyMSK

2023-08-04 07:31 UTC, tyupik requested changes

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/dto/AttachmentDTO.kt
давай немного другой путь: `data/model/dto`. Потом здесь еще появится `data/model/dao`

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +fun List<PostDTO>.postMapper(): List<PostDAO> = map(PostDAO::postMapper)
Нахрена? А главное зачем?

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
> +    private val postRepository: PostRepository
в конструктор сюда нужно передавать маппер

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
`/domain/post`
Здесь у тебя будут лежать все интеракторы для постов. Для других экранов соответственно будут свои директории

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
> +    suspend fun getAllPostList(): List<PostDAO> = postRepository.getAllPostList().postMapper()
Не нужен экстеншн для List<PostDTO>, нужно список передавать в маппер.
И почему у тебя на выходе List<PostDAO>? Для чего тебе в presentation слое DAO?

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/model/AttachmentDAO.kt
> +class AttachmentDAO(
data class

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/api/PostService.kt
> +    suspend fun getAllPostList(): Response<List<PostsItem>>
Тут было правильно, с сервера получаем PostDTO

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/dto/AttachmentDTO.kt
`/data/model/dto/`
`/data/model/dao/`

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post_screen/PostRepositoryImpl.kt
> +    override suspend fun getAllPostList(): List<PostsItem> = withContextIO {
PostDAO

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
не исправил

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
> +    private val postMapper: postMapper,
```suggestion
    private val postMapper: PostMapper,
```

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
Разбивай все по экранам, а не по видом класса.
Будет у тебя 15 экранов, будешь в папке mapper искать нужный?

`/domain/post/mapper/AttachmentMapper`

Почему у тебя названия файлов с маленькой буквы, кстати?

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +class attachmentMapper @Inject constructor() {
Почему название класса с маленькой буквы?

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +    fun mapToDao(attachment: AttachmentDTO) = AttachmentDAO(
В функциях нужно писать возвращаемый тип.

`fun mapToDao(attachment: Attachment): AttachmentDAO= ...`

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +    fun mapFromDao(attachment: AttachmentDAO) = AttachmentDTO(
```suggestion
    fun mapFromDao(attachment: AttachmentDAO): Attachment  = Attachment(
```

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +        attachment.url,
```suggestion
        url = attachment.url,
```

ниже и в других мапперах пиши имена параметров. Будет у тебя 10 штук их, не поймешь, что происходит.

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +class postMapper @Inject constructor(
Название класса

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +    private val attachmentMapper: attachmentMapper,
```suggestion
    private val attachmentMapper:  AttachmentMapper,
```

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +            it.attachment?.let { attachment ->
Имена параметров

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +            it.attachment?.let { attachment ->
Attachment у тебя входит в состав поста, можно для него не писать отдельный маппер. Сделай просто тут приватную функцию с маппером ниже и все.

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +            mentionedMe = false,
где-то написал имена параметров, где-то нет.
Везде надо писать.

2023-08-04 07:31 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/model/AttachmentDAO.kt
> +class AttachmentDAO(
не исправил

2023-08-04 18:25 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/dto/AttachmentDTO.kt
переместил

2023-08-04 18:33 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/Utils.kt
> +fun List<PostDTO>.postMapper(): List<PostDAO> = map(PostDAO::postMapper)
это я удалил

2023-08-04 18:34 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
> +    private val postRepository: PostRepository
сделано

2023-08-04 18:50 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
/domain/post создал, перенёс туда interactor, mapper, model

2023-08-04 18:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/model/AttachmentDAO.kt
> +class AttachmentDAO(
косяк, поправил

2023-08-04 19:04 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/api/PostService.kt
> +    suspend fun getAllPostList(): Response<List<PostsItem>>
исправил

2023-08-04 19:08 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/dto/AttachmentDTO.kt
AttachmentDTO перенёс. Папки создал

2023-08-04 19:13 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post_screen/PostRepositoryImpl.kt
> +    override suspend fun getAllPostList(): List<PostsItem> = withContextIO {
исправил

2023-08-04 19:15 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
> +    private val postMapper: postMapper,
конечно же с большой

2023-08-04 19:16 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
исправил

2023-08-04 19:18 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +class attachmentMapper @Inject constructor() {
конечно же с большой, поправил

2023-08-04 19:21 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +    fun mapToDao(attachment: AttachmentDTO) = AttachmentDAO(
хорошо, учту. Там где явно попались - исправил

2023-08-04 19:22 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +    fun mapFromDao(attachment: AttachmentDAO) = AttachmentDTO(
исправил

2023-08-04 19:26 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/attachmentMapper.kt
> +        attachment.url,
в AttachmentMapper и PostMapper добавил все параметры

2023-08-04 19:26 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +class postMapper @Inject constructor(
переделал на большую букву

2023-08-04 19:27 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +    private val attachmentMapper: attachmentMapper,
переделал на большую букву

2023-08-04 19:27 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +            it.attachment?.let { attachment ->
добавил

2023-08-04 19:35 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +            it.attachment?.let { attachment ->
Переделал. Названия функций длинноватые получились:
attachmentDtoToAttachmentDao()
attachmentDtoFromAttachmentDao()

Но смысл хорошо отражают

2023-08-04 19:36 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/mapper/postMapper.kt
> +            mentionedMe = false,
готово

2023-08-04 21:25 UTC, tyupik requested changes

2023-08-04 21:25 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/model/dto/AttachmentDTO.kt
> +data class AttachmentDTO(
положи в тот же файл, где PostDTO, просто ниже.
В других моделях аналогично

2023-08-04 21:25 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +    fun mapToDao(items: List<PostDTO>): List<PostDAO> = items.map { it ->
`it ->` не надо писать. Там и так по дефолту `it` будет. Если какой-то именованный параметр хочешь, то да.

2023-08-04 21:25 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/AttachmentDAO.kt
> +data class AttachmentDAO(
В PostDAO положи

2023-08-04 21:25 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/AttachmentDAO.kt
> +    val type: String,
почему String? А AttachmentTypeDAO тебе зачем?

2023-08-06 18:38 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/interactor/PostInteractor.kt
> +    suspend fun getAllPostList(): List<PostDAO> = postRepository.getAllPostList().postMapper()
это, вроде, поправил.

2023-08-06 18:46 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/dto/AttachmentDTO.kt
> +data class AttachmentDTO(
сделал для Post, PostDAO, PostDTO. 
Только есть один момент. модель ивентов тоже использует модель Attachment

2023-08-06 18:48 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +    fun mapToDao(items: List<PostDTO>): List<PostDAO> = items.map { it ->
понял, убрал

2023-08-06 18:49 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/AttachmentDAO.kt
> +data class AttachmentDAO(
Положил.
Только есть один момент. модель ивентов тоже будет использовать модель AttachmentDAO

2023-08-06 20:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/AttachmentDAO.kt
> +    val type: String,
Заменил везде String на AttachmentTypeDAO

2023-08-07 15:03 UTC, tyupik requested changes

2023-08-07 15:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Attachment.kt
> +    val type: AttachmentTypeDAO,
`AttachmentTypeDAO` положи в этот же файл, но ниже

2023-08-07 15:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Post.kt
> +data class Post(
почему в дата слое оказался Post?

2023-08-07 15:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/model/dto/AttachmentDTO.kt
> +data class AttachmentDTO(
Обсудили в телеге, `AttachmentDTO` будет отдельным файлом

2023-08-07 15:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +    fun mapToDao(items: List<PostDTO>): List<PostDAO> = items.map { it ->
Точно убрал?

2023-08-07 15:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +    )
Attachment будет и на ивентах использоваться. Вынеси это в отдельный маппер для Attachment.

2023-08-07 15:03 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/mapper/PostMapper.kt
> +    )
у тебя уже был этот код. Бери из отедельного маппера.

2023-08-07 15:08 UTC, tyupik requested changes

2023-08-07 15:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Attachment.kt
>  data class Attachment(
Dao? Dto?

2023-08-07 15:08 UTC, tyupik commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/AttachmentTypeDAO.kt
> +enum class AttachmentTypeDAO {
Почему Dao в домейн слое? Как рум узнает об этой модели?

2023-08-07 18:40 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +    fun mapToDao(items: List<PostDTO>): List<PostDAO> = items.map { it ->
теперь да)

2023-08-07 19:01 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Post.kt
> +data class Post(
упс.. перенёс в presentation

2023-08-07 19:02 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Post.kt
> +data class Post(
вместе с ивентами и другими

2023-08-07 19:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Attachment.kt
> +    val type: AttachmentTypeDAO,
Оставил только AttachmentType в data

2023-08-07 19:53 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Attachment.kt
> +    val type: AttachmentTypeDAO,
AttachmentType вложил в Attachment

2023-08-07 19:54 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Post.kt
> +data class Post(
перенёс в domain

2023-08-07 19:55 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/post/mapper/PostMapper.kt
> +    )
готово

2023-08-07 19:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/mapper/PostMapper.kt
> +    )
Оставил только Attachment и AttachmentType. AttachmentMapper больше не нужен - удалил

2023-08-07 19:56 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/data/model/Attachment.kt
>  data class Attachment(
Оставил только Attachment и AttachmentType, как обговорили

2023-08-07 19:57 UTC, WoodyMSK commented on app/src/main/java/ru/woodymsk/socialapp/domain/post/model/AttachmentTypeDAO.kt
> +enum class AttachmentTypeDAO {
Оставил только Attachment и AttachmentType в data, как обговорили

2023-08-07 20:45 UTC, tyupik approved these changes

2023-08-07 20:46 UTC, merged